### ISSUE TITLE
[pywebview] WebView2 initialization failed with exception.

### ISSUE THREAD

**Issue by 7gxycn08** [r0x0r/pywebview#1012]
### Specification
- pywebview version: 3.7.2
- operating system: Windows 11 Pro
- web renderer: Default

### Description  
  
  Getting this exception when running two apps that use pywebview.
`[pywebview] WebView2 initialization failed with exception:
  (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()`
  
### Practicalities

- YES I am willing to work on this issue myself.

.- YES I am prepared to support this issue financially..

**Comment by r0x0r** [comment]
Sorry I have no idea. What Edge runtime have you got installed?

**Comment by 7gxycn08** [comment]
Are asking about `(Get-AppxPackage -Name "Microsoft.MicrosoftEdge").Version`
it says: `44.22621.1037.0`
