### ISSUE TITLE
test failure: test_move_window.py

### ISSUE THREAD

**Issue by keredson** [r0x0r/pywebview#1043]
### Specification
- pywebview version: 

```
derek@wash:~/projects/pywebview/tests$ git show HEAD
commit 864bffece9e79ef2905fcf14c5e40925658135a2 (HEAD -> master, origin/master, origin/HEAD)
Merge: c53b57b 7930109
Author: Roman <roman@flowrl.com>
Date:   Mon Feb 6 21:36:50 2023 +0200

    Merge pull request #1032 from max-uho/master
    
    non-QUERTY keyboard shortcuts

derek@wash:~/projects/pywebview/tests$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

- operating system:

```
derek@wash:~/projects/pywebview/tests$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
```

- web renderer:  GTK I assume

### Description  
  
```
============================================ FAILURES =============================================
________________________________________ test_move_window _________________________________________

    def test_move_window():
        window = webview.create_window('Move window test', x=200, y=200, width=100, height=100)
>       run_test(webview, window, move_window)
E       Failed: Traceback (most recent call last):
E         File "/home/derek/projects/pywebview/tests/util.py", line 65, in thread
E           thread_func(window)
E         File "/home/derek/projects/pywebview/tests/test_move_window.py", line 25, in move_window
E           assert window.x == 100
E       AssertionError: assert 1974 == 100
E        +  where 1974 = <webview.window.Window object at 0x7fb106086b90>.x

tests/test_move_window.py:13: Failed
---------------------------------------- Captured log call ----------------------------------------
ERROR    pywebview:util.py:69 assert 1974 == 100
 +  where 1974 = <webview.window.Window object at 0x7fb106086b90>.x
Traceback (most recent call last):
  File "/home/derek/projects/pywebview/tests/util.py", line 65, in thread
    thread_func(window)
  File "/home/derek/projects/pywebview/tests/test_move_window.py", line 25, in move_window
    assert window.x == 100
AssertionError: assert 1974 == 100
 +  where 1974 = <webview.window.Window object at 0x7fb106086b90>.x
================================== 1 failed, 2 warnings in 3.16s ==================================
```
  
I have a dual monitor setup going right now (1920x1200 next to 3840x2160):
![image](https://user-images.githubusercontent.com/2049665/218548077-fbdd8d3c-f74e-4bb4-b3f4-9852f371c803.png)

If I switch to a single display or I move the smaller display so it's in the upper-left, the test passes.  So I assume it's because it's trying to move the window to a coordinate outside the display area.  Probably a non-issue in real-life use, just documenting.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a known issue. I have attempted to fix it, but coordinates returned by different platforms are vastly different. If you find a fix, please submit a PR.
