### ISSUE TITLE
How to get a Flask executable that runs without the console attached?

### ISSUE THREAD

**Issue by DanArruda** [r0x0r/pywebview#1054]
### Specification
Pywebview version: 4.0.1
Flask version: 2.2.3
Pyinstaller version: 5.8.0
operating system: Windows 10: 

### Description  
  
 When I try to run an executable created with auto-py-to-exe from a Flask application, it throws this error:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\http.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'

This is the "code" used in ayto-py-to-exe:

`pyinstaller --noconfirm --onedir --windowed --add-data "C:/xxxxxxx/PycharmProjects/pythonFlaskApi/templates;templates/" --add-data "C:/xxxxxx/PycharmProjects/pythonFlaskApi/static;static/" --add-data "C:/xxxxxxxxx/PycharmProjects/pythonFlaskApi/venv/Lib/site-packages/webview/lib/WebBrowserInterop.x64.dll;." --add-data "C:/xxxxxxxx/PycharmProjects/pythonFlaskApi/venv/Lib/site-packages/webview/lib/WebBrowserInterop.x86.dll;." --python-option ""  "C:/xxxxxxxx/PycharmProjects/pythonFlaskApi/main.py"`

main.py code:
```

from flask import Flask, render_template
import webview

app = Flask(__name__, template_folder='templates', static_folder='static')

window = webview.create_window('Myapp', app)


@app.route('/', methods=['GET'])
def index():
    return render_template('index.html')

if __name__ == '__main__':
    webview.start()
```

The executable only works if console-based mode selected in pyinstaller.. But I don't want the console to be seen.

**Comment by DanArruda** [comment]
Thank you! Worked.
