### ISSUE TITLE
Failed to execute script test due to unhandled exception: a bytes-like object is required not str

### ISSUE THREAD

**Issue by kletel** [r0x0r/pywebview#1102]
### Specification
- pywebview version:  pywebview==4.0.2
- operating system: windows 11
- web renderer: Edge chromium

### Description  
  
a simple test.py file : 

import webview
import os
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
webview.start()
  
generate an exe with pyinstaller pyinstaller==5.10.1 : 
pyinstaller --debug all  --log-level DEBUG --clean --uac-admin --noconsole --windowed --onedir test.py

execute the test.exe program generated : 
 
Error : Failed to execute script test due to unhandled exception: a bytes-like object is required not str

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "webview\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "webview\http.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1144, in get_code
  File "<frozen importlib._bootstrap_external>", line 674, in _compile_bytecode
  File "<frozen importlib._bootstrap>", line 249, in _verbose_message
  File "tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'

I tried with the storage path too : 
import webview
import os
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
storagepath = os.path.join(os.getenv('LOCALAPPDATA'), "test")
webview.start(storage_path=storagepath)

same error.

it works with the previous version pywebview==3.6.2
![Capture d’écran 2023-04-19 162854](https://user-images.githubusercontent.com/51789742/233107494-f59cb70b-5b95-4bc8-87fc-3959021148c8.png)

**Comment by Borecjeborec1** [comment]
Have you tried
```python
import webview
webview.create_window(title='Hello world', url='https://pywebview.flowrl.com/hello')
webview.start()
```

This solved my issue on win10. I think it happens because when compiled, the positional arguments are expected as strings, but when compiling they are already bites. When you use this approach, the named arguments are passed the same as they are required.

If the code above did not work either, try creating variables to ensure they are stored in the right type.
```python
import webview
name = 'Hello world' 
link = 'https://pywebview.flowrl.com/hello'
webview.create_window(title=name, url=link)
webview.start()
```

Hope I helped ;D

**Comment by kletel** [comment]
it solved with this little test app but not with a bigger app

**Comment by kletel** [comment]
The debug mode is not working as well

**Comment by Borecjeborec1** [comment]
Have you used the `debug=False`. I think it is the same problem as above. 
Also when I try `debug=some_variable`, both True and False work after compiling with pyinstaller. 

Maybe the values you are passing are not really booleans. (I have not tried what this results in after compiling, but this could be the problem)

**Comment by r0x0r** [comment]
@kletel the tempfile issue has been fixed in master. 
What do you mean by debug mode not working? When frozen with pyinstaller?

**Comment by kletel** [comment]
It's working with the master branch, frozen with pyinstaller and the debug mode is working too.
