### ISSUE TITLE
 WebView2 initialization failed 

### ISSUE THREAD

**Issue by nadaa** [r0x0r/pywebview#1184]
### Specification
- pywebview version: 4.2.2
- operating system: windows 11 pro
- web renderer: Microsoft Edge 115.0.1901.183 (Official build) (64-bit)

### Description

I got this error when I run the desktop application. It was working before resetting windows and reinstallation.

```
[pywebview] WebView2 initialization failed with exception:
[1]  The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
[1]    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
[1]    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
[1] --- End of stack trace from previous location where exception was thrown ---
[1]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[1]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[1]    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
[1] ERROR:pywebview:WebView2 initialization failed with exception:
[1]  The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
```
Simply I run webview by
`webview.start(http_server=False)
`

Any idea on how to solve this?

Thanks
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There is something wrong with your setup. Is the machine you are running it on has restricted access?
Googling for "webview2 0x80070002" might be a good starting point.
