### ISSUE TITLE
webview.platforms not found in Linux

### ISSUE THREAD

**Issue by chdominguez** [r0x0r/pywebview#1188]
### Specification
- pywebview version: 4.2.2
- operating system: Ubuntu/Rocky Linux
- web renderer: GTK

### Description

  Long story short I am developing a multiplatform App that runs on macOS, Ubuntu and Rocky Linux. On macOS the app runs perfectly fine and I am able to package it into a .app with PyInstaller.
  
  On the other hand, It seems impossible to make a 'compiled' version of the app working. Whereas the app works fine if I do `python myapp.py', once I bundle it with PyInstaller the following error appears:
  
```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 25, in import_gtk
ModuleNotFoundError: No module named 'webview.platforms'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "webview/guilib.py", line 37, in import_qt
ModuleNotFoundError: No module named 'webview.platforms'
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "webview/__init__.py", line 154, in start
  File "webview/guilib.py", line 109, in initialize
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```

The problem is very easy to reproduce, just create a "view.py" file and try to bundle the Hello World example: 
```
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```

Then:
`pyinstaller --onefile view.py`

To clarify:
The app works perfectly fine when not bundled, therefore I expect the error to be in the PyInstaller hook. PyInstaller version: 5.13.0 (2023-06-24)

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by chdominguez** [comment]
Nevermind, I was using pywebview 4.2 instead of 4.2.2. In the latest version the issue is fixed.
