### ISSUE TITLE
Issue Cannot call null pointer from Cdata

### ISSUE THREAD

**Issue by RaiFernandesdosSantos** [r0x0r/pywebview#1190]
### Specification
- python version: 3.11
- pywebview version: 4.2.2
- pythonnet version: 3.0.1
- clr-loader vesion: 0.2.5
- .net frameword: 7.0.9
- operating system: windows 11
- web renderer: microsoft edge 115.0.1901.188

### Description

  pywebview will not open a window when the script is executed. I create a simple script called main.py and used the contents included on the page [https://pywebview.flowrl.com/] for testing purposes. The lines in the script are:

import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()

When I execute the script via a CMD prompt on my Window 11 machine the following error is produced in the CMD window and nothing happens:

Command:
C:\Users\desktop\python>python.exe teste.py

Return
Traceback (most recent call last):
File "C:\Users\Usuário\Desktop\programacao\Python\GeradorDeSenhas\teste.py", line 4, in <module>
    webview.start()
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\__init__.py", line 154, in start
    guilib = initialize(gui)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 119, in initialize
    if not try_import(guis):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 71, in try_import
    if import_func():
       ^^^^^^^^^^^^^
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 60, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\platforms\winforms.py", line 12, in <module>
    import clr
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
       ^^^^^^^^^
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python311\Lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

### Practicalities

- YES / am willing to work on this issue myself.

- NO / I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a pythonnet issue. This might be of help https://github.com/pythonnet/pythonnet/issues/1617
