### ISSUE TITLE
Pyinstaller/Pythonnet/Clr_loader strongly documented issue, at a dead end.  'Failed to resolve Python.Runtime' // 'cannot call null pointer pointer from cdata' 

### ISSUE THREAD

**Issue by samfisherirl** [r0x0r/pywebview#1215]
### Specification
- pywebview version: python 3.9.3
- secondary python versions tested  3.10.11 
- operating system: win 10 / win 11
- web renderer: Webview2

### Checking the boxes

Yes to all:

- am I using a fresh install?
- am I using a virtual machine w/ or w/o a venv?
- am I using pyinstaller debug?
- am I using a simplified script? 
- have I installed Net Framework / webview ? 

### Description

I cannot get a compiled pywebview app to run consistently on windows machines for simple pywebview apps. It crashes with the error below before starting. I have used pywebview for 2+ years, and only recently tried seriously to compile. 

I am running 3 machines.

- 1 laptop windows 11 64x
- 1 desktop windows 10 64x
- 1 virtual machine - various windows 10 installs 64x

If I install on the Desktop, it doesn't run on the Laptop. 
Sometimes it'll run on the laptop once, then I restart my Laptop and it doesnt run again. 
If I setup the EXE on a virtual machine, it won't run on my Desktop.

There seems to be an issue with:

- Pythonnet and clr_loader
- Within virtualenvs
- not recognizing paths (I have added to setup scripts the paths, but I dont know how to setup the path dotenv mentioned places) 

primary reference ma24 2023: https://github.com/pythonnet/pythonnet/issues/1617#issuecomment-1560989364

another reference: https://github.com/pyinstaller/pyinstaller/issues/7412#issuecomment-1433050599 

- another source discussing the issue: https://stackoverflow.com/a/75412605/16233233

All have NET framework 4.7, all have webview installed. 
I have read the **entire** pythonnet relevant documentation
I have read the two paragraphs on freezing in pywebview. 
I have read the issue pages that provide these solutions (only after running into issues, originally I followed directions):

- Installing pythonnet 3.0.2a (or 3.0.0a, cant remember which) with clr_loader 0.17
- Include with pyinstaller --hidden-import=clr_loader 
- include with pyinstaller --hidden-import=pythonnet
- include with pyinstaller --hidden-import=webview 
- 

I have pywebview apps going back 3-4 years. this has come up now and then. I decided to start out writing a production application and finally took this issue seriously and it seems to be very tough to follow, and net framework/dotnet documentation is quite impenetrable. I do appreciate your time and consideration, I look forward to feedback.  

 
### code

I have a larger app, but just to get things tested, Im getting the exact same error and have been using this. 

```python

"""This example demonstrates how to create and manage multiple windows."""

import webview


def third_window():
    # Create a new window after the loop started
    third_window = webview.create_window('Window #3', html='<h1>Third Window</h1>')


if __name__ == '__main__':
    # Master window
    master_window = webview.create_window('Window #1', html='<h1>First window</h1>')
    second_window = webview.create_window('Window #2', html='<h1>Second window</h1>')
    webview.start(third_window)

```

### Errors 

These are the errors Im getting on a consistent basis. 

## Primary error

```python


Traceback (most recent call last):
  File "main.py", line 54, in <module>
  File "main.py", line 51, in main
  File "webview\__init__.py", line 155, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 43, in load
  File "clr_loader\wrappers.py", line 20, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

```

## Secondary error 

```python
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "webview\__init__.py", line 155, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\Sam\Downloads\main\main\pythonnet\runtime\Python.Runtime.dll
[8700] Failed to execute script 'main' due to unhandled exception!
```

one iteration of my setup.py:

```batch

pyinstaller --onedir --hidden-import=clr_loader --clean --hidden-import=pythonnet --hidden-import=webview --paths "C:\Users\dower\AppData\Local\Programs\Python\Python310"     --add-data "C:\Users\dower\Desktop\test_py_folder\venv\Lib\site-packages\webview\lib\WebBrowserInterop.x64.dll;./" --add-data "C:\Users\dower\Desktop\test_py_folder\venv\Lib\site-packages\webview\lib\WebBrowserInterop.x86.dll;./"  --add-data "C:\Users\dower\Desktop\test_py_folder\venv\Lib\site-packages\webview\lib\Microsoft.Web.WebView2.Core.dll;./" --add-data "C:\Users\dower\Desktop\test_py_folder\venv\Lib\site-packages\webview\lib\Microsoft.Web.WebView2.WinForms.dll;./"  --exclude-module "tkinter" main.py


```

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by samfisherirl** [comment]
@answer 

after a week of pulling out hair, I managed to fix this with the install going on a fresh windows fresh python virtual machine. Something about my path, my variables, and my environment was causing it.

**Comment by samfisherirl** [comment]
potentially my solution, ill need feedback. Maybe im doing something wrong. It seems pyinstaller was keeping the path in the app on delivery. 


```python
from pythonnet import set_runtime
set_runtime("netfx")

from os import environ
from pathlib import Path
runtim = Path.cwd() / "python310.dll"

if runtim.exists():
    environ["PYTHONNET_PYDLL"] = str(runtim.resolve())
    environ["BASE_DIR"] = str(Path.cwd().resolve())

# original example 



def third_window():
    # Create a new window after the loop started
    third_window = webview.create_window('Window #3', html='<h1>Third Window</h1>')


if __name__ == '__main__':
    # Master window
    master_window = webview.create_window('Window #1', html='<h1>First window</h1>')
    second_window = webview.create_window('Window #2', html='<h1>Second window</h1>')
    webview.start(third_window)

**Comment by r0x0r** [comment]
Thanks for investigating this issue. I am not familiar with this problem and it has been a while since I have used pyinstaller. 
Do you think your solution can be incorporated in the pywebview code base?

**Comment by samfisherirl** [comment]
> Thanks for investigating this issue. I am not familiar with this problem and it has been a while since I have used pyinstaller. Do you think your solution can be incorporated in the pywebview code base?

I found the issue to be in using --onedir on computer without python. 

fix- nuitka --onefile or pyinstaller --onefile



Ill ask briefly you check on this pull request that went stale - 
I think separate javacscript examples for get and send data to/from js to py would be helpful, I spent a good amount of time on formatting for pywebview's github. If you have time just to glance at it, let me know! closing issue. 


https://github.com/samfisherirl/PyWebview-Send-Form-to-Python-Template

**Comment by r0x0r** [comment]
The main purpose of examples is to showcase pywebview's features, not to address individual cases. 
There is also a `window.get_elements` function for getting DOM nodes,

**Comment by kilbasar** [comment]
For others who might come across this issue via google search: I was having this same `RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize` error, only on Windows Server 2016 (no error on 2019 or 2022). For me the workaround was to pin `pythonnet` to version `2.5.2`; both `3.0.1` and latest `3.0.3` exhibited this issue.

**Comment by Eboubaker** [comment]
Iinstalled .net 4.5.0 I got error about failure to load clrloader.dll so i installed .net 4.7.0(after the root certifcates update) then the error changed to:
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen elmeftah-mod>", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tkwebview2\tkwebview2.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\me\AppData\Local\Temp\_MEI34162\pythonnet\runtime\Python.Runtime.dll
```

**Comment by Eboubaker** [comment]
UPDATE: So I was packaging my application on a windows 10 x32bit i checked which .net framework was installed via the cmd command;
```
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version
```
It said 4.8.0 so i went in my windows 7 and installed .net 4.8.0 now my program works fine!
