### ISSUE TITLE
[pywebview] GTK cannot be loaded

### ISSUE THREAD

**Issue by MananSachdeva1817** [r0x0r/pywebview#1240]
### Specification
- pywebview version: 4.3.3
- operating system: ubuntu 22.04
- web renderer: 

### Description

file.py >>>>
import webview
window = webview.create_window('Woah dude!', 'https://pywebview.flowrl.com')
webview.start()

this error comes when i do>     python file.py
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/manpreetsingh7/venv/leap/lib/python3.10/site-packages/webview/guilib.py", line 25, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/manpreetsingh7/venv/leap/lib/python3.10/site-packages/webview/platforms/gtk.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
QSocketNotifier: Can only be used with threads started with QThread 

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by MananSachdeva1817** [comment]
CLOSES
