### ISSUE TITLE
Unhandled Exception when trying to use pywebview on windows 10 with py2.7.13 x64

### ISSUE THREAD

**Issue by adamclmns** [r0x0r/pywebview#127]
I'm running with the Anaconda version of Python -     
    **python --version
    Python 2.7.13 :: Continuum Analytics, Inc. 64bit**
Installed pythonnet and pywebview 1.7
Created a main.py 
     **import webview
     webview.create_window(“It works, Jim!”, “http://www.flowrl.com”)**
When running this, I get the following error in terminal.

Unhandled Exception: Python.Runtime.PythonException: TypeError : no constructor matches given arguments
   **at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()**

I'm running Windows 10, if that helps. I've been unable to get this to work, even when installing pywin32. 

This happens in a virtualenv, or in the system root python installation. I'm unable to find any work around.

**Comment by r0x0r** [comment]
Could you test if you get it working with the regular Python distribution?

**Comment by adamclmns** [comment]
I just tried the 64 bit version of 2.7.13 and it works fine. Closing the issue here and will start looking at Anaconda to solve this. 

Thanks!
