### ISSUE TITLE
AppDelegate is overriding existing Objective-C class

### ISSUE THREAD

**Issue by benmaxyoung** [r0x0r/pywebview#1280]
### Specification
- pywebview version: 4.4.1
- operating system: macOS 14.1.2 (23B92)
- web renderer: Cocoa

### Description
An error occurred while executing `briefcase run -r -u`
```
/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/escpos/capabilities.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
2023-12-06 16:37:47.007 Python[35737:541116] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Error in handler: AppDelegate is overriding existing Objective-C class
Traceback (most recent call last):
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/toga/handlers.py", line 79, in _handler
    result = handler(interface, *args, **kwargs)
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/testwb/src/testwb/app.py", line 56, in to_webview
    webview.start()
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/__init__.py", line 155, in start
    guilib = initialize(gui)
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/guilib.py", line 97, in initialize
    if not try_import(guis):
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/guilib.py", line 71, in try_import
    if import_func():
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/guilib.py", line 48, in import_cocoa
    import webview.platforms.cocoa as guilib
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/platforms/cocoa.py", line 63, in <module>
    class BrowserView:
  File "/Users/ben/Work/Test/Code/BeeWare/TestWB/beeware-venv/lib/python3.9/site-packages/webview/platforms/cocoa.py", line 70, in BrowserView
    class AppDelegate(AppKit.NSObject):
objc.error: AppDelegate is overriding existing Objective-C class
```

app.py
```
import toga

import webview


class TestWB(toga.App):

    def startup(self):
        window = webview.create_window('Woah dude!', 'https://google.com')
        webview.start()


def main():
    return TestWB()

```

pyproject.toml
```
requires = [
    "pywebview",
]
...
```

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry no idea about this error or whether briefcase is compatible with _pywebview_. Maybe removing AppDelegate helps, but that will remove closing event functionality.
pywebview 5.0 will have Android support.
