### ISSUE TITLE
Problems when run on Windows - Bootstrap error

### ISSUE THREAD

**Issue by paulocoutinhox** [r0x0r/pywebview#1316]
### Specification
- pywebview version: latest
- operating system: windows 
- web renderer: auto

### Description

Im getting this erros when execute on Windows:
![image](https://github.com/r0x0r/pywebview/assets/395096/0380ab79-ba1e-4c8f-8a8f-c8563d2d1ffe)

Project is here:
https://github.com/paulocoutinhox/dataxow/releases/tag/main-0a291d4

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by paulocoutinhox** [comment]
The application running with "python3 src/backend\main.py" works, but not from pyinstaller.

Can anyone help me understand?

**Comment by r0x0r** [comment]
Check this issue
https://github.com/pyinstaller/pyinstaller/issues/1801

Adding might help
`hiddenimports=['clr_loader', 'pythonnet']`

**Comment by paulocoutinhox** [comment]
Hi,

I add it:
https://github.com/paulocoutinhox/dataxow/commit/b5fca5468683ca0fa4eae7dc223779e71b602fd0

But still with error:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "webview\__init__.py", line 155, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\rebec\Downloads\artifact-windows-x64.zip (1)\windows-x64\dist\DataXow\_internal\pythonnet\runtime\Python.Runtime.dll
```

**Comment by paulocoutinhox** [comment]
I tried adding `clr` and `crl_loader`, but the error still happen.
  
https://github.com/pyinstaller/pyinstaller/issues/8294

**Comment by paulocoutinhox** [comment]
I check now that if i create from my local windows machine it works.

Maybe something need be installed github action? Make sense?

**Comment by paulocoutinhox** [comment]
Hi,

There is a problem on Windows and pythonnet or something internal in pywebview dependencies.

When i unblock before extract, it works. The user need do this before use the app.

There is a way to Windows trust in this file?

Or, there is a way where we don't need pythonnet (use only CEF, for example)? Because in my project with CEF and Qt, i don't have problem with this:

- https://github.com/paulocoutinhox/cef-sample
- https://github.com/paulocoutinhox/prprojector

The thread about this problem on Windows is here:
https://github.com/pyinstaller/pyinstaller/issues/8294

Thanks.
