### ISSUE TITLE
Error in `pip install pywebview` with Python 3.13

### ISSUE THREAD

**Issue by xianfei** [r0x0r/pywebview#1517]
### Specification
- pywebview version:5.3.2
- operating system:windows 11
- python: 3.13.0

### Description

I encountered an issue while using this library with the newly released Python 3.13. It seems that the issue is caused by a compatibility problem with the Pythonnet dependency. 

```
PS C:\Users\xianfei> pip install pywebview
Collecting pywebview
  Using cached pywebview-5.3.2-py3-none-any.whl.metadata (4.2 kB)
Collecting proxy-tools (from pywebview)
  Using cached proxy_tools-0.1.0-py3-none-any.whl
Collecting bottle (from pywebview)
  Using cached bottle-0.13.2-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting typing-extensions (from pywebview)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting pythonnet (from pywebview)
  Downloading pythonnet-2.5.2.tar.gz (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycparser (from pythonnet->pywebview)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached pywebview-5.3.2-py3-none-any.whl (452 kB)
Using cached bottle-0.13.2-py2.py3-none-any.whl (104 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pythonnet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [218 lines of output]
      <string>:468: SyntaxWarning: invalid escape sequence '\*'
      <string>:533: SyntaxWarning: invalid escape sequence '\*'
      C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py:251: _IncompatibleBdistWheel: wheel.bdist_wheel is deprecated, please import it from setuptools
      !!

              ********************************************************************************
              Ensure that any custom bdist_wheel implementation is a subclass of
              setuptools.command.bdist_wheel.bdist_wheel.

              By 2025-Oct-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://github.com/pypa/wheel/pull/631 for details.
              ********************************************************************************

      !!
        return _build_backend().build_wheel(wheel_directory, config_settings,
      <string>:468: SyntaxWarning: invalid escape sequence '\*'
      <string>:533: SyntaxWarning: invalid escape sequence '\*'
      running bdist_wheel
      running build
      running build_ext
      正在检查来自 https://www.nuget.org/api/v2/ 的更新。
      当前正在运行 NuGet.exe 4.1.0。
      正在将 NuGet.exe 更新到 6.11.1。
      更新成功。
      找不到指定版本的 msbuild:“14”
      MSBuild 自动检测: 使用来自 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319" 的 msbuild 版本 "4.0"。
      C:\Users\xianfei\AppData\Local\Temp\NuGetScratch\sbb4bztx.dae.nugetrestore.targets(125,23): error MSB4066: 无法识 别元素 <PackageReference> 中的特性“Version”。 [C:\Users\xianfei\AppData\Local\Temp\NuGetScratch\r503nku3.bqp.nugetinputs.targets]

      警告: 读取 msbuild 项目信息时出错，请确保输入解决方案或项目文件有效。将跳过 NETCore 和 UAP 项目，仅还原 packages.config 文件。
      Restoring NuGet package System.ValueTuple.4.5.0.
      Restoring NuGet package NUnit.3.12.0.
      Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
      Restoring NuGet package UnmanagedExports.1.2.7.
      Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Adding package 'NUnit.3.12.0' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
      Added package 'NUnit.3.12.0' to folder 'C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\packages'
        CACHE https://api.nuget.org/v3/vulnerabilities/index.json
        CACHE https://api.nuget.org/v3-vulnerabilities/2024.10.29.23.52.14/vulnerability.base.json
        CACHE https://api.nuget.org/v3-vulnerabilities/2024.10.29.23.52.14/2024.10.29.23.52.14/vulnerability.update.json

      使用的 NuGet 配置文件:
          C:\Users\xianfei\AppData\Roaming\NuGet\NuGet.Config

      使用的源:
          C:\Users\xianfei\.nuget\packages\
          https://api.nuget.org/v3/index.json

      已安装:
          packages.config projects 的 4 包
      Traceback (most recent call last):
        File "C:\Users\xianfei\AppData\Local\Temp\pip-install-vgsr_iw0\pythonnet_7a7623a0e5c843619f2a7faedf4e0ae0\tools\geninterop\geninterop.py", line 29, in <module>
          from pycparser import c_ast, c_parser
      ModuleNotFoundError: No module named 'pycparser'
      Traceback (most recent call last):
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\fancy_getopt.py", line 245, in getopt
          opts, args = getopt.getopt(args, short_opts, self.long_opts)
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\getopt.py", line 93, in getopt
          opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
                       ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\getopt.py", line 157, in do_longs
          has_arg, opt = long_has_args(opt, longopts)
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\getopt.py", line 174, in long_has_args
          raise GetoptError(_('option --%s not recognized') % opt, opt)
      getopt.GetoptError: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 170, in setup
          ok = dist.parse_command_line()
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 472, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\dist.py", line 901, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 576, in _parse_command_opts
          (args, opts) = parser.getopt(args[1:])
                         ~~~~~~~~~~~~~^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\fancy_getopt.py", line 247, in getopt
          raise DistutilsArgError(msg)
      distutils.errors.DistutilsArgError: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 437, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 425, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 406, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 630, in <module>
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          raise SystemExit(gen_usage(dist.script_name) + f"\nerror: {msg}")
      SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 443, in build_wheel
          return _build(['bdist_wheel'])
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 425, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 406, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 630, in <module>
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "<string>", line 612, in run
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_vendor\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\xianfei\AppData\Local\Temp\pip-build-env-lev2sjtf\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "<string>", line 302, in build_extension
        File "C:\Users\xianfei\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\xianfei\\AppData\\Local\\Programs\\Python\\Python313\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop313.cs']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pythonnet
Failed to build pythonnet

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pythonnet)
PS C:\Users\xianfei>
```

**Comment by Barafu** [comment]
That is on `pythonnet`. Until they fix it, nothing can be done here.

**Comment by xianfei** [comment]
In fact, `webview.start(gui='qt')` is working well on python 3.13 and windows, with `pip install pyside6 qtpy`. Although an error occurred during installation.

![image](https://github.com/user-attachments/assets/f8265eae-0e2a-409f-8d23-0e8951416c53)

**Comment by xianfei** [comment]
[Pythonnet v3.0.5](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.5) already supports 3.13 now.
