### ISSUE TITLE
TypeError: 'Window' object is not callable

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1524]
### Specification
- pywebview version:  5.3.2
- operating system: Ubuntu 24.04.1 LTS

### Description

i run project so show this error but project working fine but show this error in console

  Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'Window' object is not callable

**Comment by MominIqbal-1234** [comment]
this issue is solved 
 window = webview.create_window(software_name,
                                   app,text_select=True,width=1300, 
                                   height=700,min_size=(1300,700),confirm_close=True
                                   ) # min_size=(1200,700)
    
    webview.start(window, # i can pass the window variable
        debug=False,
                  http_server=True,
                  http_port=9000,
                  icon=f"{static}/icon/logo.ico",
                   menu=menu_items,
                  )
