### ISSUE TITLE
Unable to create a basic window no matter what. (Library problems?)

### ISSUE THREAD

**Issue by 0hStormy** [r0x0r/pywebview#1558]
### Specification
- pywebview version: 5.3.2
- operating system: Fedora Linux 41
- web renderer: QT hopefully, GTK as a backup

### Description

I am 99% sure I have installed all dependencies, all I'm doing is this:

``` py
import webview

webview.create_window('Channels', 'index.html')
webview.start(ssl=True, gui='qt')
```

But I get this as output and then it closes:

``` sh
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/stormy/.local/lib/python3.13/site-packages/webview/platforms/qt.py", line 35, in <module>
    from qtpy.QtWebEngineWidgets import QWebEnginePage as QWebPage
  File "/home/stormy/.local/lib/python3.13/site-packages/qtpy/QtWebEngineWidgets.py", line 28, in <module>
    from PyQt5.QtWebEngineWidgets import (
    ...<5 lines>...
    )
ImportError: /home/stormy/.local/lib/python3.13/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stormy/.local/lib/python3.13/site-packages/webview/guilib.py", line 49, in import_qt
    import webview.platforms.qt as guilib
  File "/home/stormy/.local/lib/python3.13/site-packages/webview/platforms/qt.py", line 42, in <module>
    from PyQt5 import QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/usr/lib64/python3.13/site-packages/PyQt5/__init__.py)
Gdk-Message: 12:17:26.134: Error 71 (Protocol error) dispatching to Wayland display.
```
To summerize the log, it's saying that it can't import QtWebKitWidgets and `~/.local/lib/python3.13/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5` is considered an "undefined symbol" while trying to import (library issue?).

I tried also forcing it to run in X11 but that just gave me even less helpful GTK errors.

### Practicalities

- YES I am willing to work on this issue myself. (As long as it doesn't involve having to compile pywebview myself)

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I am not familiar with Fedora, but it looks like you are missing the libQt5WebEngineCore package, which usually needs to be installed separately. Googling for "fedora libQt5WebEngineCore" might provide a clue, eg https://rpmfind.net/linux/rpm2html/search.php?query=libQt5WebEngineCore.so.5
