### ISSUE TITLE
NameError: name 'gui' is not defined

### ISSUE THREAD

**Issue by taewookim** [r0x0r/pywebview#163]
Python 3.6
Windows 8

I keep getting this error when  i try to run example/js_api.py

Tried pip installing these:

> pip install pywebview[winforms]
> pip install pywebview[win32]

Full error log:

> Traceback (most recent call last):
>   File "js_api.py", line 131, in <module>
>     webview.create_window('API example', debug=True, js_api=api)
> TypeError: create_window() got an unexpected keyword argument 'debug'
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Anaconda3\lib\site-packages\webview\__init__.py", line 161, in load_html
>     gui.load_html(_make_unicode(content), base_uri)
> NameError: name 'gui' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Anaconda3\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "js_api.py", line 123, in create_app
>     webview.load_html(html)
>   File "C:\Anaconda3\lib\site-packages\webview\__init__.py", line 163, in load_html
>     raise Exception("Create a web view window first, before invoking this function")
> Exception: Create a web view window first, before invoking this function
>

**Comment by r0x0r** [comment]
I just pushed a fix. Try now.

**Comment by Swardu** [comment]
I have the same issue, Windows 10. Installed using pip 10minutes ago.

**Comment by r0x0r** [comment]
@Swardu `js_api` is not the release version of pywebview. Could you be more specific with the error you get?

**Comment by shivaprsdv** [comment]
@taewookim @Swardu In the `examples` directory, make a symlink to the
`webview` directory. These new examples won't work with the pip installed
version. They use code that haven't been released yet.

**Comment by r0x0r** [comment]
Another way to run an example from a checked out copy of pywebview is:
`PYTHONPATH=. python examples/js_api.py` (in the pywebview root directory)

**Comment by shivaprsdv** [comment]
Didn't know this. Thanks for the tip!

**Comment by Swardu** [comment]
Using the one from scripting-object branch, I got this error.

`
Traceback (most recent call last):
  File "c:\Users\HugsPC\Desktop\python\memberry\init.py", line 119, in <module>
    webview.create_window('API example', js_api=api)
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\__init__.py", line 198, in create_window
    _initialize_imports()
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\__init__.py", line 97, in _initialize_imports
    import webview.winforms as gui
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\winforms.py", line 21, in <module>
    clr.AddReference(os.path.join(base_dir, 'lib', 'WebBrowserInterop'))
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\lib\WebBrowserInterop'.
   at Python.Runtime.CLRModule.AddReference(String name)
File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\winforms.py", line 21, in <module>
    clr.AddReference(os.path.join(base_dir, 'lib', 'WebBrowserInterop'))
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\lib\WebBrowserInterop'.
   at Python.Runtime.CLRModule.AddReference(String name)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\__init__.py", line 171, in load_html
    gui.load_html(_make_unicode(content), base_uri)
NameError: name 'gui' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\HugsPC\Desktop\python\memberry\init.py", line 111, in create_app
    webview.load_html(html)
  File "C:\Users\HugsPC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\webview\__init__.py", line 173, in load_html
    raise Exception("Create a web view window first, before invoking this function")
Exception: Create a web view window first, before invoking this function
`

The file WebBrowserInterop.dll exists in that path.

**Comment by Swardu** [comment]
EDIT: Fixed it by changing it to 
`
clr.AddReference(os.path.join(base_dir, 'lib', 'WebBrowserInterop.dll'))`

**Comment by taewookim** [comment]
@r0x0r Did you check in the fix? Same error and latest commit  i see is: 

> Latest commit ca42e62  on Dec 4, 2017

**Comment by shivaprsdv** [comment]
Did you check out `scripting-object`? You seem to be on `master`.

**Comment by taewookim** [comment]
@shivaprsdv I think im confused. can you tell me where that is?

**Comment by shivaprsdv** [comment]
I mean, he merged your code into the `scripting-object` branch. Have you
checked it out using `git checkout scripting-object`?

**Comment by Swardu** [comment]
You can click right here to see the scripting-object branch: https://github.com/r0x0r/pywebview/tree/scripting-object

**Comment by taewookim** [comment]
ran:

> wget https://github.com/r0x0r/pywebview/archive/scripting-object.zip
> unzip scripting-object.zip; cd pywebview-scripting-object
> python setup.py install

Still same error.

**Comment by r0x0r** [comment]
@taewookim try checking out the scripting-object and running the js_api example without installing

**Comment by taewookim** [comment]
i pip uninstalled pywebview first
then

> $ python js_api.py
> Traceback (most recent call last):
>   File "js_api.py", line 1, in <module>
>     import webview
> ModuleNotFoundError: No module named 'webview'
>

**Comment by r0x0r** [comment]
See [this comment](https://github.com/r0x0r/pywebview/issues/163#issuecomment-355737595) on how to run an example with a checked out copy of pywebview

**Comment by taewookim** [comment]
Weird... that worked

If anyone was wondering about syntax:

> wget https://github.com/r0x0r/pywebview/archive/scripting-object.zip
> unzip scripting-object.zip; cd pywebview-scripting-object
> PYTHONPATH=. python examples/js_api.py

Yeah the 3rd line is odd, but it works

**Comment by taewookim** [comment]
Does this mean this issue needs to be closed? not sure if this means the problem is solved or it's my environment or what

**Comment by r0x0r** [comment]
It is a standard Bash way of setting an environmental variable in the context of the executed command

**Comment by taewookim** [comment]
thanks for your help @r0x0r

**Comment by taewookim** [comment]
IN this case, how do I freeze the app?

i tried 

`PYTHONPATH=. pyinstaller examples/js_api.py`

but i get this error:

```
$ PYTHONPATH=. pyinstaller examples/js_api.py
531 INFO: PyInstaller: 3.3.1
531 INFO: Python: 3.6.2
531 INFO: Platform: Windows-8.1-6.3.9600-SP0
531 INFO: wrote C:\cygwin64\home\T\security\client\pywebview-scripting-object\js_api.sp                                  ec
531 INFO: UPX is not available.
531 INFO: Extending PYTHONPATH with paths
['C:\\cygwin64\\home\\T\\security\\client\\pywebview-scripting-object\\examples',
 'C:\\cygwin64\\home\\T\\security\\client\\pywebview-scripting-object']
531 INFO: checking Analysis
531 INFO: Building Analysis because out00-Analysis.toc is non existent
531 INFO: Initializing module dependency graph...
546 INFO: Initializing module graph hooks...
546 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "C:\Anaconda3\lib\pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Anaconda3\lib\pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "C:\Anaconda3\lib\inspect.py", line 41, in <module>
    import linecache
  File "C:\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "C:\Anaconda3\lib\pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Anaconda3\lib\pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "C:\Anaconda3\lib\inspect.py", line 41, in <module>
    import linecache
  File "C:\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
4442 INFO: running Analysis out00-Analysis.toc
4458 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Anaconda3\python.exe
5083 INFO: Caching module hooks...
5098 INFO: Analyzing C:\cygwin64\home\T\security\client\pywebview-scripting-object\examples\js_api.py
5936 INFO: Processing pre-safe import module hook   win32com
6061 INFO: Processing pre-find module path hook   distutils
14058 INFO: Processing pre-find module path hook   site
14058 INFO: site: retargeting to fake-dir 'C:\\Anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
17721 INFO: Loading module hooks...
17721 INFO: Loading module hook "hook-clr.py"...
17721 INFO: Loading module hook "hook-distutils.py"...
17721 INFO: Loading module hook "hook-encodings.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "C:\Anaconda3\lib\pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Anaconda3\lib\pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "C:\Anaconda3\lib\inspect.py", line 41, in <module>
    import linecache
  File "C:\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
17872 INFO: Loading module hook "hook-lib2to3.py"...
17872 INFO: Loading module hook "hook-numpy.core.py"...
17935 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
17935 INFO: Loading module hook "hook-pkg_resources.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "C:\Anaconda3\lib\pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Anaconda3\lib\pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "C:\Anaconda3\lib\inspect.py", line 41, in <module>
    import linecache
  File "C:\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
18200 INFO: Loading module hook "hook-pycparser.py"...
18450 INFO: Loading module hook "hook-pydoc.py"...
18450 INFO: Loading module hook "hook-PyQt5.py"...
18450 INFO: Loading module hook "hook-PyQt5.Qt.py"...
18450 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
18606 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
19325 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
19481 INFO: Loading module hook "hook-PyQt5.QtWebKitWidgets.py"...
19481 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
19481 INFO: Loading module hook "hook-pytest.py"...
20731 INFO: Loading module hook "hook-pythoncom.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Anaconda3\lib\site-packages\PyInstaller\__init__.py", line 16, in <module>
    from . import compat
  File "C:\Anaconda3\lib\site-packages\PyInstaller\compat.py", line 20, in <module>
    import platform
  File "C:\Anaconda3\lib\platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
20903 INFO: Loading module hook "hook-pywintypes.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Anaconda3\lib\site-packages\PyInstaller\__init__.py", line 16, in <module>
    from . import compat
  File "C:\Anaconda3\lib\site-packages\PyInstaller\compat.py", line 20, in <module>
    import platform
  File "C:\Anaconda3\lib\platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "C:\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
21060 INFO: Loading module hook "hook-setuptools.py"...
21075 INFO: Loading module hook "hook-sysconfig.py"...
21075 INFO: Loading module hook "hook-win32com.py"...
21872 INFO: Loading module hook "hook-xml.dom.domreg.py"...
21872 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
21872 INFO: Loading module hook "hook-xml.py"...
21872 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
21997 INFO: Loading module hook "hook-PyQt5.QtWebKit.py"...
22013 INFO: Looking for ctypes DLLs
22138 WARNING: library coredll required via ctypes not found
22153 INFO: Analyzing run-time hooks ...
22153 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
22153 INFO: Including run-time hook 'pyi_rth_pkgres.py'
22153 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
22153 INFO: Including run-time hook 'pyi_rth_qt5.py'
22169 INFO: Looking for dynamic libraries
22169 INFO: Cannot get manifest resource from non-PE file .eggs\modulegraph-0.16-py3.6.egg\modulegraph\__init__.py
22169 WARNING: Can not get binary dependencies for file: .eggs\modulegraph-0.16-py3.6.egg\modulegraph\__init__.py
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 721, in getImports
    return _getImports_pe(pth)
  File "C:\Anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 103, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)
  File "C:\Anaconda3\lib\site-packages\pefile.py", line 1746, in __init__
    self.__parse__(name, data, fast_load)
  File "C:\Anaconda3\lib\site-packages\pefile.py", line 1831, in __parse__
    raise PEFormatError('Unable to read the DOS Header, possibly a truncated file.')
pefile.PEFormatError: 'Unable to read the DOS Header, possibly a truncated file.'
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\pyinstaller-script.py", line 5, in <module>
    sys.exit(PyInstaller.__main__.run())
  File "C:\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "C:\Anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 537, in assemble
    redirects=self.binding_redirects))
  File "C:\Anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 222, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 400, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Anaconda3\lib\site-packages\PyInstaller\depend\bindepend.py", line 351, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\Anaconda3\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1005, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Anaconda3\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 168, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (2, 'LoadLibraryEx', 'The system cannot find the file specified.')

```

**Comment by taewookim** [comment]
BTW.. if anyone else is getting this error:

`AttributeError: module 'enum' has no attribute 'IntFlag'`


it's b/c of [this error ](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag)

you can fix by 

> pip uninstall enum34
