### ISSUE TITLE
error on Windows when trying example in readme

### ISSUE THREAD

**Issue by heftlanded** [r0x0r/pywebview#2]
the error i'm getting is:

Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "<module1>", line 3, in <module>
  File "C:\Python27\lib\site-packages\webview\main.py", line 72, in create_window
    gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscreen)
  File "C:\Python27\lib\site-packages\webview\win32.py", line 233, in create_window
    browser_view = BrowserView(title, url, width, height, resizable, fullscreen)
  File "C:\Python27\lib\site-packages\webview\win32.py", line 157, in __init__
    self.create_main_window()
  File "C:\Python27\lib\site-packages\webview\win32.py", line 177, in create_main_window
    None, None, BrowserView.wndclass.hInstance, None)
pywintypes.error: (1407, 'CreateWindowEx', 'Cannot find window class.')

could the error be related to amd64 version i'm using?

**Comment by r0x0r** [comment]
What Python distribution are you using?

**Comment by heftlanded** [comment]
I am using Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32.

**Comment by r0x0r** [comment]
I just pushed a new version, which should fix the problem. Would you mind giving it a try and see if it works?

**Comment by heftlanded** [comment]
thank you sir, works perfectly now.
