### ISSUE TITLE
How to freeze app on linux

### ISSUE THREAD

**Issue by fgrzadkowski** [r0x0r/pywebview#254]
### Specification
- Platform: Linux / Ubuntu
- Version: 2.0.3

### Description
How do I freeze app on Linux which uses pywebview? Documentation only says about OSX and Windows. I tried pyinstaller, which is recommended for Windows, but I get the following errors:

```ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "webview/__init__.py", line 81, in _initialize_imports
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/filip/code/control-server-ui/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "webview/gtk.py", line 25, in <module>
  File "gi/__init__.py", line 127, in require_version
ValueError: Namespace WebKit not available
ERROR:webview:QT cannot be loaded
Traceback (most recent call last):
  File "webview/__init__.py", line 90, in _initialize_imports
  File "/home/filip/code/control-server-ui/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "webview/qt.py", line 68, in <module>
ImportError: This module requires PyQt4 or PyQt5 to work under Linux or *BSD.
Traceback (most recent call last):
  File "webview/__init__.py", line 90, in _initialize_imports
  File "/home/filip/code/control-server-ui/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "webview/qt.py", line 68, in <module>
ImportError: This module requires PyQt4 or PyQt5 to work under Linux or *BSD.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ui.py", line 34, in <module>
  File "webview/__init__.py", line 176, in create_window
  File "webview/__init__.py", line 95, in _initialize_imports
Exception: You must have either QT or GTK with Python extensions installed in order to use this library.
[16169] Failed to execute script ui
Exception in thread Thread-1:
Traceback (most recent call last):
  File "webview/__init__.py", line 132, in wrapper
  File "webview/__init__.py", line 233, in load_html
NameError: name 'gui' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "ui.py", line 26, in create_app
  File "webview/__init__.py", line 134, in wrapper
Exception: Create a web view window first, before invoking this function
```

**Comment by fgrzadkowski** [comment]
Output from pyinstaller

```
$ ./venv/bin/pyinstaller ./src/ui.py 
24 INFO: PyInstaller: 3.5.dev0+98fe28542
24 INFO: Python: 3.5.2
25 INFO: Platform: Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
25 INFO: wrote /home/filip/code/control-server-ui/ui.spec
26 INFO: UPX is not available.
27 INFO: Extending PYTHONPATH with paths
['/home/filip/code/control-server-ui/src', '/home/filip/code/control-server-ui']
27 INFO: checking Analysis
291 INFO: Building because /home/filip/code/control-server-ui/src/ui.py changed
291 INFO: Initializing module dependency graph...
292 INFO: Initializing module graph hooks...
293 INFO: Analyzing base_library.zip ...
2305 INFO: running Analysis Analysis-00.toc
2325 INFO: Caching module hooks...
2328 INFO: Analyzing /home/filip/code/control-server-ui/src/ui.py
2475 INFO: Processing pre-safe import module hook   gi.repository.Gtk
2476 INFO: Processing pre-safe import module hook   gi.repository.Gdk
2476 INFO: Processing pre-safe import module hook   gi.repository.GLib
2496 INFO: Processing pre-safe import module hook   win32com
2504 INFO: Loading module hooks...
2504 INFO: Loading module hook "hook-xml.py"...
2669 INFO: Loading module hook "hook-encodings.py"...
2710 INFO: Loading module hook "hook-gi.repository.GLib.py"...
2975 INFO: Loading module hook "hook-gi.py"...
2975 INFO: Loading module hook "hook-gi.repository.Gdk.py"...
3071 INFO: Processing pre-safe import module hook   gi.repository.cairo
3071 INFO: Processing pre-safe import module hook   gi.repository.Pango
3072 INFO: Processing pre-safe import module hook   gi.repository.Gio
3072 INFO: Processing pre-safe import module hook   gi.repository.GdkPixbuf
3072 INFO: Loading module hook "hook-gi.repository.Gio.py"...
3214 INFO: Processing pre-safe import module hook   gi.repository.GObject
3215 INFO: Loading module hook "hook-pydoc.py"...
3215 INFO: Loading module hook "hook-gi.repository.Gtk.py"...
4149 INFO: Processing pre-safe import module hook   gi.repository.xlib
4149 INFO: Processing pre-safe import module hook   gi.repository.Atk
4150 INFO: Loading module hook "hook-gi.repository.GdkPixbuf.py"...
4300 INFO: Processing pre-safe import module hook   gi.repository.GModule
4304 INFO: Loading module hook "hook-gi.repository.xlib.py"...
4388 INFO: Loading module hook "hook-gi.repository.Pango.py"...
4475 INFO: Loading module hook "hook-gi.repository.cairo.py"...
4558 INFO: Loading module hook "hook-gi.repository.GObject.py"...
4657 WARNING: Hidden import "gi._gobject" not found!
4657 INFO: Loading module hook "hook-gi.repository.GModule.py"...
4742 INFO: Loading module hook "hook-gi.repository.Atk.py"...
4935 INFO: Looking for ctypes DLLs
5000 WARNING: library atl.dll required via ctypes not found
5074 INFO: Analyzing run-time hooks ...
5077 INFO: Including run-time hook 'pyi_rth_glib.py'
5077 INFO: Including run-time hook 'pyi_rth_gdkpixbuf.py'
5079 INFO: Including run-time hook 'pyi_rth_gio.py'
5079 INFO: Including run-time hook 'pyi_rth_gtk.py'
5080 INFO: Including run-time hook 'pyi_rth_gi.py'
5083 INFO: Looking for dynamic libraries
6808 INFO: Looking for eggs
6809 INFO: Python library not in binary dependencies. Doing additional searching...
6872 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
6876 INFO: Warnings written to /home/filip/code/control-server-ui/build/ui/warn-ui.txt
6895 INFO: Graph cross-reference written to /home/filip/code/control-server-ui/build/ui/xref-ui.html
7499 INFO: checking PYZ
7500 INFO: Building because toc changed
7500 INFO: Building PYZ (ZlibArchive) /home/filip/code/control-server-ui/build/ui/PYZ-00.pyz
7736 INFO: Building PYZ (ZlibArchive) /home/filip/code/control-server-ui/build/ui/PYZ-00.pyz completed successfully.
7739 INFO: checking PKG
7739 INFO: Building because /home/filip/code/control-server-ui/build/ui/PYZ-00.pyz changed
7739 INFO: Building PKG (CArchive) PKG-00.pkg
7783 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
7783 INFO: Bootloader /home/filip/code/control-server-ui/venv/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-64bit/run
7784 INFO: checking EXE
7784 INFO: Rebuilding EXE-00.toc because pkg is more recent
7784 INFO: Building EXE from EXE-00.toc
7785 INFO: Appending archive to ELF section in EXE /home/filip/code/control-server-ui/build/ui/ui
7791 INFO: Building EXE from EXE-00.toc completed successfully.
7832 INFO: checking COLLECT
WARNING: The output directory "/home/filip/code/control-server-ui/dist/ui" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
11552 INFO: Removing dir /home/filip/code/control-server-ui/dist/ui
12456 INFO: Building COLLECT COLLECT-00.toc
17603 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```
