### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by gzliuqingyun** [r0x0r/pywebview#266]
### Specification
- Platform:  win10 64bit
- Version: 

### Description
When html/js make request in a loop, after a while, it will cause:
```
Unprocessed Exception:  System.AccessViolationException: try to read or write protected memory
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
  at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw)
```

The html/js code is like:
```
    var a = 0;
    var intervalID = setInterval(function(){
        $('#device_status').text(a+=1);
        pywebview.api.get_selected_device().then(function(response){
            $('#device_status').text(JSON.stringify(response));
        });
    }, 100);
```

**Comment by gzliuqingyun** [comment]
Is there any alternatives? I need to query device status every second, make request from js(front) to python(backend).

**Comment by r0x0r** [comment]
The thing is I have not managed to reproduce it since the first time. I have been running an infinite js api loop for several hours without a crash now. I have created a test based on the js_api.py in the `windows-crash-test` branch. Click on Hello Python button and it will start a loop.

As for your question refactoring your code to flow data in the other direction might do the trick. Ie you can place a loop in the Python code that would invoke evaluate_js to poll Javascript values.
