### ISSUE TITLE
global name 'Gdk' is not defined

### ISSUE THREAD

**Issue by Loknar** [r0x0r/pywebview#28]
Hello, I'm having some beginner problems with this. Any help greatly appreciated.

I'm on ubuntu 14.04 LTS, using a python 2.7 virtualenv setup. I installed the module via `pip install pywebview`.

I'm running the following simple example:
```
import webview
webview.create_window('It works, Jim!', 'http://www.flowrl.com')
```
and getting the following exception:
```
(env1_v1)loknar@turninn:~/repo/webview-test$ python webview_test.py 
WARNING:webview.qt:PyQt4 is not found
WARNING:webview.qt:PyQt5 is not found
WARNING:webview:QT not found
WARNING:webview.gtk:PyGObject is not found
Traceback (most recent call last):
  File "/home/loknar/.virtualenvs/env1_v1/local/lib/python2.7/site-packages/webview/gtk.py", line 15, in <module>
    from gi.repository import Gtk as gtk
ImportError: No module named gi.repository
Traceback (most recent call last):
  File "webview_test.py", line 6, in <module>
    webview.create_window('It works, Jim!', 'http://www.flowrl.com')
  File "/home/loknar/.virtualenvs/env1_v1/local/lib/python2.7/site-packages/webview/__init__.py", line 94, in create_window
    gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscreen, min_size)
  File "/home/loknar/.virtualenvs/env1_v1/local/lib/python2.7/site-packages/webview/gtk.py", line 116, in create_window
    browser = BrowserView(title, url, width, height, resizable, fullscreen, min_size)
  File "/home/loknar/.virtualenvs/env1_v1/local/lib/python2.7/site-packages/webview/gtk.py", line 31, in __init__
    Gdk.threads_init()
NameError: global name 'Gdk' is not defined
(env1_v1)loknar@turninn:~/repo/webview-test$
```
Additional info:
```
(env1_v1)loknar@turninn:~$ sudo apt-get install python-qt4
[sudo] password for loknar:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-qt4 is already the newest version.
The following packages were automatically installed and are no longer required:
  account-plugin-windows-live libc-ares2 libupstart1 linux-headers-3.16.0-30
  linux-headers-3.16.0-30-generic linux-headers-3.16.0-40
  linux-headers-3.16.0-40-generic linux-headers-generic-lts-utopic
  linux-image-3.16.0-30-generic linux-image-3.16.0-40-generic
  linux-image-extra-3.16.0-30-generic linux-image-extra-3.16.0-40-generic
  linux-image-generic-lts-utopic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

**Comment by r0x0r** [comment]
What Python distribution are you using? Is it the one that came with Ubuntu or a custom install?
 
Try installing PyQt4 or PyGObject using these guides
http://askubuntu.com/questions/419945/how-does-one-install-pygobject-from-the-official-repository
https://forum.qt.io/topic/44636/how-to-install-pyqt-5-on-ubuntu/4

**Comment by r0x0r** [comment]
I am closing this issue, as it is a local environment problem.
