### ISSUE TITLE
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: No support for x86

### ISSUE THREAD

**Issue by vanillycpp** [r0x0r/pywebview#281]
### Specification
- Platform: Win7 x86
- Version:  pywebview-2.2.1

### Description
run hellow world
```
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
```

have this error
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: No support for x86
   at Python.Runtime.TypeManager.NativeCode.get_Active()
   at Python.Runtime.TypeManager.InitializeNativeCodePage()
   at Python.Runtime.TypeManager.InitializeSlots(IntPtr type, Type impl)
   at Python.Runtime.TypeManager.CreateMetaType(Type impl)
   at Python.Runtime.MetaType.Initialize()
   at Python.Runtime.Runtime.Initialize()
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```
have this log while pywebview install
```
Collecting pywebview
  Using cached https://files.pythonhosted.org/packages/9c/98/2bb83cbe35b09bf5079684f3eeecba2f19d0c90c5cac0ca272539d058d7d/pywebview-2.2.1-py3-none-any.whl
Requirement already satisfied: pythonnet; sys_platform == "win32" in c:\python37\lib\site-packages (from pywebview) (2.4.0.dev0)
Installing collected packages: pywebview
Successfully installed pywebview-2.2.1
```

**Comment by r0x0r** [comment]
I don't have a Windows 7 environment ready, but a couple of questions first.
a) What .NET version do you have installed?
b) Does pythonnet work for you?
c) start Python and execute this commands. 
```
import clr

clr.AddReference('System.Windows.Forms')
clr.AddReference('System.Threading')

import System.Windows.Forms as WinForms
from System import IntPtr, Int32, Func, Type, Environment
from System.Threading import Thread, ThreadStart, ApartmentState
from System.Drawing import Size, Point, Icon, Color, ColorTranslator, SizeF
```
Does this work?

**Comment by r0x0r** [comment]
As a workaround, you may try installing an older version of pythonnet. As far as I know pywebview  does not rely on any pythonnet features that would require the latest version.

I am closing this issue now. If you find a resolution, please post it here for a reference.

**Comment by denfromufa** [comment]
@vanillycpp the installation for your platform (win7 32-bit) has been fixed in pythonnet
