### ISSUE TITLE
l can't load gtk

### ISSUE THREAD

**Issue by kkyflying** [r0x0r/pywebview#300]
### Specification
- Platform: ubuntu 16.04 py3 
- Version:  
PyQt5      5.11.3 
PyQt5-sip  4.19.13
pywebview  2.2.1  

### Description
ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "/home/code/python/web-gui/web-gui-env/lib/python3.5/site-packages/webview/__init__.py", line 66, in import_gtk
    import webview.gtk as gui
  File "/home/code/python/web-gui/web-gui-env/lib/python3.5/site-packages/webview/gtk.py", line 26, in <module>
    import gi
ImportError: No module named 'gi'

l follow this url [Installation](https://pywebview.flowrl.com/guide/installation.html)
```
sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0

```
&&
```
sudo apt install python3-pyqt5 python3-pyqt5.qtwebkit libqt5webkit5-dev 
```
the pywebview had install in  virtualenv_env

**Comment by r0x0r** [comment]
What is the output of `sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0`? Did it find all the packages?

**Comment by kkyflying** [comment]
thank you , l had fix this problem, just can't find the packages
