### ISSUE TITLE
SyntaxError Exception in Windows

### ISSUE THREAD

**Issue by lwanger** [r0x0r/pywebview#33]
I get a series of SyntaxError exceptions (see below for an example) when I create a window under Windows 10. It happens with any URL I load. Here is an example of the code:

import webview
webview.create_window("title", "http://google.com")

Sample from the stack trace:

ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
Traceback (most recent call last):
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\_comobject.py", line 147, in call_without_this
    result = mth(*inargs)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Users\Admin\AppData\Roaming\Python\Python35\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "c:\anaconda\envs\py35\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 32518
    True = 1
           ^
SyntaxError: can't assign to keyword

**Comment by r0x0r** [comment]
It is a bug in the comtypes code generator. The fix has been made to the comtypes master branch, but there is no a proper release yet. To fix this you have to monkey patch c:\anaconda\envs\py35\lib\site-packages\comtypes\tools\codegenerator.py. [Here is the diff](https://github.com/enthought/comtypes/pull/95/files)

**Comment by lwanger** [comment]
Thanks!

Len

Date: Fri, 27 May 2016 13:44:38 -0700

**Comment by r0x0r** [comment]
I am closing this issue.
