### ISSUE TITLE
True = 1

### ISSUE THREAD

**Issue by Henk3** [r0x0r/pywebview#37]
Hi, I'm running the newest version of python (3.5.1 i think) and the example is giving me stack traces.

`import webview

webview.create_window("It works, Jim!", "http://www.flowrl.com")`

prints lots of these to stderr (the program does keep running):

`SyntaxError: can't assign to keyword
# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 88274
    True = 1
           ^
SyntaxError: can't assign to keyword
ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\_comobject.py", line 147, in call_without_this
    result = mth(*inargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 88274
    True = 1
           ^
SyntaxError: can't assign to keyword`

And they just keep coming after each `# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0`

**Comment by Henk3** [comment]
@r0x0r My bad, closed issues should be more visible on GitHub.
