### ISSUE TITLE
Non-integer screenwidth

### ISSUE THREAD

**Issue by Firnagzen** [r0x0r/pywebview#4]
Running windows XP, Python 3.3, attempting to create a window returned the error:
```
        Traceback (most recent call last):
          File "C:\Documents and Settings\user1\Desktop\pywebview-master\pywebview-master\examples\http_serv
        er.py", line 32, in <module>
            webview.create_window("My first HTML5 application", "http://127.0.0.1:23948")
          File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\main.py", line 72, in create_w
        indow
            gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscree
        n)
          File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 214, in create
        _window
            browser_view = BrowserView(title, url, width, height, resizable, fullscreen)
          File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 121, in __init
        __
            self._create_main_window()
          File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 160, in _creat
        e_main_window
            None, None, self.wndclass.hInstance, None)
        TypeError: integer argument expected, got float
```
Suggested fix to win32.py:
```
        def _create_main_window(self):
            # Set window style
            style = win32con.WS_VISIBLE
            if self.resizable:
                style = style | win32con.WS_OVERLAPPEDWINDOW
            else:
                style = style | (win32con.WS_OVERLAPPEDWINDOW ^ win32con.WS_THICKFRAME)

            #  Center window on the screen
            screen_x = _user32.GetSystemMetrics(win32con.SM_CXSCREEN)
            screen_y = _user32.GetSystemMetrics(win32con.SM_CYSCREEN)
            x = int((screen_x - self.width) / 2)
            y = int((screen_y - self.height) / 2)
```

**Comment by r0x0r** [comment]
Thanks. Fixed in the latest version.

**Comment by Firnagzen** [comment]
Fixed.
