### ISSUE TITLE
Getting issue regarding comtypes on Win7-64bit

### ISSUE THREAD

**Issue by neRok00** [r0x0r/pywebview#41]
I'm just testing this package out, and whilst it is working, I am getting some errors in the console output. The full console text is below.

    127.0.0.1 - - [04/Aug/2016 12:20:04] "GET / HTTP/1.1" 200 204
    # Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
    Traceback (most recent call last):
      File "myvirtualenv\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
        return func(*args, **kw)
      File "myvirtualenv\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
        custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
      File "myvirtualenv\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
        return GetBestInterface(punk)
      File "myvirtualenv\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
        mod = GetModule(tlib)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
        mod = _CreateWrapper(tlib, pathname)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
        mod = _my_import(fullname)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
        return __import__(fullname, globals(), locals(), ['DUMMY'])
      File "myvirtualenv\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 90917
        True = 1
               ^
    SyntaxError: can't assign to keyword
    ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
    Traceback (most recent call last):
      File "myvirtualenv\lib\site-packages\comtypes\_comobject.py", line 147, in call_without_this
        result = mth(*inargs)
      File "myvirtualenv\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
        return func(*args, **kw)
      File "myvirtualenv\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
        custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
      File "myvirtualenv\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
        return GetBestInterface(punk)
      File "myvirtualenv\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
        mod = GetModule(tlib)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
        mod = _CreateWrapper(tlib, pathname)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
        mod = _my_import(fullname)
      File "myvirtualenv\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
        return __import__(fullname, globals(), locals(), ['DUMMY'])
      File "myvirtualenv\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 90917
        True = 1
               ^
    SyntaxError: can't assign to keyword

**Comment by neRok00** [comment]
BTW, when the line `# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0` appears in the console, the program hangs for a few seconds.

**Comment by r0x0r** [comment]
See #33
