### ISSUE TITLE
flask_app example throwing exceptions, crashes

### ISSUE THREAD

**Issue by rgmrtn** [r0x0r/pywebview#459]
### Specification
- pywebview version: latest
- platform / version: Windows 10 - Python 3.7.2

```
Package      Version
------------ -------
Click        7.0
Flask        1.1.1
itsdangerous 1.1.0
Jinja2       2.10.3
MarkupSafe   1.1.1
pip          20.0.1
pythonnet    2.4.0
pywebview    3.1
setuptools   45.1.0
Werkzeug     0.16.0
wheel        0.33.6
```
### Description  
  
  Example app won't load. Message below:

```
> python src\backend\main.py

 * Running on http://127.0.0.1:23948/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Jan/2020 12:47:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 12:47:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 12:47:28] "POST /init HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 12:47:28] "GET /favicon.ico HTTP/1.1" 404 -

Unhandled Exception: Python.Runtime.PythonException: Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
  
### Practicalities

- YES/NO I am willing to work on this issue myself. 
Willing, but unable.
- YES/NO I am prepared to support this issue financially.
Not at this time. Excited to test out pywebview when it works for me.

**Comment by r0x0r** [comment]
I cannot reproduce it. Can you run any other examples?

**Comment by rgmrtn** [comment]
No, the other examples produce the same result, testing on a different machine with a fresh virtualenv.

```
(webview) C:\Users\rgmrtn\python_apps\webview\pywebview\examples>python qt_test.py

Unhandled Exception: Python.Runtime.PythonException: Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by r0x0r** [comment]
Looks like you are trying to run it as an administrator. Please run it under normal user account. More details here https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/13

Your other options are is using MSHTML (ie Internet explorer)  or CEF. See https://pywebview.flowrl.com/guide/renderer.html for details.

**Comment by rgmrtn** [comment]
Interesting, it asks for admin level permissions after opening the example, but this solved my issue. CEF is likely the way to go. Thanks @r0x0r
