### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Nearata** [r0x0r/pywebview#463]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10 Home (1909)

### Description  
  
'NoneType' object has no attribute 'replace' when creating a window from another window.

### Code

```
# main.py

class Api():
    ...
    def second_window(self, window_title):
        try:
            create_window(window_title, "assets/second.html")
        except Exception as e:
            print(e)

if __name__ == "__main__":
    api = Api()
    create_window("Main", "assets/index.html", js_api=api, min_size=(600, 450))
    start()
```
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Could you post full stack-trace?

**Comment by Nearata** [comment]
```
Traceback (most recent call last):
  File "main.py", line 41, in second_window
    create_window(show_title, "assets/second.html")
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\__init__.py", line 139, in create_window
    guilib.create_window(window)
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\platforms\winforms.py", line 658, in create_window
    i.Invoke(Func[Type](create))
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\platforms\winforms.py", line 625, in create
    browser = BrowserView.BrowserForm(window)
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\platforms\winforms.py", line 385, in __init__
    self.browser = BrowserView.EdgeHTML(self, window)
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\platforms\winforms.py", line 252, in __init__
    self.load_url(window.url)
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\platforms\winforms.py", line 290, in load_url
    url = start_server(self.url)
  File "C:\Users\Nearata\.virtualenvs\vvvvid-downloader-WuCH19jy\lib\site-packages\webview\http_server.py", line 72, in start_server
    base_path = os.path.dirname(url.replace('file://', ''))
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by Nearata** [comment]
i fixed it by passing `window.location.href` to the api and replacing `index` with `second`

```
def second_window(self, window_title):
    create_window(window_title, url.replace("index", "second"))
```
