### ISSUE TITLE
Exception from HRESULT: 0x80010007 (RPC_E_SERVER_DIED) when excuting webview.start()

### ISSUE THREAD

**Issue by dodiameer** [r0x0r/pywebview#481]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10 / Python 3.7 in venv

### Description  
  
  Using TODOS example, executing `webview.start()`, I get this error:
`Unhandled Exception: Python.Runtime.PythonException: Exception : The callee (server [not    server application]) is not available and disappeared; all connections are invalid. The call may hav
e executed. (Exception from HRESULT: 0x80010007 (RPC_E_SERVER_DIED))
`
  
### Practicalities

- NO I am not willing to work on this issue myself as I do not have enough knowledge. 

- NO I am not prepared to support this issue financially as I don't believe it is going to require ny support.

**Comment by r0x0r** [comment]
A wild guess, are you trying to run it as an administrator? WebView is rather buggy, and for one does not work when run as an admin. It throws a different exception, though.

**Comment by dodiameer** [comment]
I actually was running as admin,but that doesn't change anything :(

I realized I forgot to include the whole console output so here it is:
`Unhandled Exception: Python.Runtime.PythonException: Exception : The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call may have executed. (Exception from HRESULT: 0x80010007 (RPC_E_SERVER_DIED))
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by r0x0r** [comment]
Can you run any other examples? E.g. simple_browser.py?

**Comment by dodiameer** [comment]
Exact same output when I ran simple_browser.py. seems to be an issue with pywebview itself

**Comment by r0x0r** [comment]
What .NET and Windows 10 version are you running? The only mention to this error I found is this https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/223 and it is of no help.

Meanwhile you may use either CEF as a renderer.

**Comment by dodiameer** [comment]
Windows 10 Pro Version 1909 Build 18363.418
.NET Core SDK 3.1.100
.NET Framework 4.6.1 
CEF seems to work for me so I'll stick to that while we figure out a solution.

**Comment by dodiameer** [comment]
Tried Updating .NET framework to 4.6.2 to see if it changes anything and it tells me that it's already installed. if framework version makes a difference, I might just reinstall Windows.

**Comment by r0x0r** [comment]
To be honest Edge-based WebView is buggy af and it seems Microsoft has abandoned it since they announced transition to Chromium. WebView2 is coming out at some point, so I would wait till it arrives.
