### ISSUE TITLE
pip install pyttsx3

### ISSUE THREAD

**Issue by Umashankar1411** [r0x0r/pywebview#485]
Collecting pyttsx3
  Using cached https://files.pythonhosted.org/packages/f4/20/f6c582c5f2735ca5c55ae52f1ddbc7447fb3565b5ac2fdc24a8d534f4aa1/pyttsx3-2.84-py3-none-any.whl
Collecting pyobjc>=2.4 (from pyttsx3)
  Using cached https://files.pythonhosted.org/packages/b1/c9/83b256bb7f771a9e4232518005d6f237ae79215283cf5ea234141751b36a/pyobjc-6.1-py3-none-any.whl
Collecting comtypes; "win32" in sys_platform (from pyttsx3)
  Using cached https://files.pythonhosted.org/packages/fb/b8/f8aa21774acb4535e32f6a89055876ca497ff806f9b1b1912b469284a61e/comtypes-1.1.7.zip
Collecting pyobjc-framework-CoreWLAN==6.1; platform_release >= "10.0" (from pyobjc>=2.4->pyttsx3)
  Downloading https://files.pythonhosted.org/packages/2b/aa/a45fbb0bd2da6643454c72c0438c711e294f939184b277a996e4862ed2ef/pyobjc-framework-CoreWLAN-6.1.tar.gz (45kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pycharm-packaging\pyobjc-framework-CoreWLAN\setup.py", line 27, in <module>
        for fn in os.listdir("Modules")
      File "C:\Users\HP\AppData\Local\Temp\pycharm-packaging\pyobjc-framework-CoreWLAN\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\HP\AppData\Local\Temp\pycharm-packaging\pyobjc-framework-CoreWLAN\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pycharm-packaging\pyobjc-framework-CoreWLAN\

**Comment by r0x0r** [comment]
How is this related to pywebview?

**Comment by Umashankar1411** [comment]
@r0x0r no.. I am creating using pucharm...an chatbot which can talk... but its giving an error that pyttsx3 can't be installed due to above error... if u have any idea pls help me out bro...
