### ISSUE TITLE
svcVersion not in registry keys

### ISSUE THREAD

**Issue by Firnagzen** [r0x0r/pywebview#5]
Running Windows XP, python 3.3:
```
    Traceback (most recent call last):
      File "C:\Documents and Settings\user1\Desktop\pywebview-master\pywebview-master\examples\http_serv
    er.py", line 32, in <module>
        webview.create_window("My first HTML5 application", "http://127.0.0.1:23948")
      File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\main.py", line 72, in create_w
    indow
        gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscree
    n)
      File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 213, in create
    _window
        set_ie_mode()
      File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 265, in set_ie
    _mode
        mode = get_ie_mode()
      File "C:\Python33\lib\site-packages\pywebview-0.5-py3.3.egg\webview\win32.py", line 245, in get_ie
    _mode
        version, type = winreg.QueryValueEx(ie_key, "svcVersion")
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Suggested fix to win32.py:

    def get_ie_mode():
        """
        Get the installed version of IE
        :return:
        """
        ie_key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r'Software\Microsoft\Internet Explorer')
        try:
            version, type = winreg.QueryValueEx(ie_key, "svcVersion")
        except FileNotFoundError:
            version, type = winreg.QueryValueEx(ie_key, "Version")
        winreg.CloseKey(ie_key)

**Comment by r0x0r** [comment]
Thanks. Fixed in the latest version.
Apologies for the slow response. Github did not notify me for some reason.

**Comment by Firnagzen** [comment]
Yep, that works.
