### ISSUE TITLE
Issue with pip installation

### ISSUE THREAD

**Issue by niklaskeerl** [r0x0r/pywebview#508]
### Specification
- pywebview version: 3.2
- platform / version: Platform: Windows 10 Version 1903, Python 3.8.2, pip 20.0.2

### Description  
  
Installing pywebview on Linux worked like a charm! Now, I wanted to test it out on windows. I went with the installation guide: https://pywebview.flowrl.com/guide/installation.html

The first time I ran the command, this happened:
```
C:\Users\karin>pip install pywebview
Collecting pywebview
  Using cached pywebview-3.2-py3-none-any.whl (115 kB)
Collecting pythonnet; sys_platform == "win32"
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\karin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-hft_9e6h\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-hft_9e6h\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\karin\AppData\Local\Temp\pip-install-hft_9e6h\pythonnet\pip-egg-info'
         cwd: C:\Users\karin\AppData\Local\Temp\pip-install-hft_9e6h\pythonnet\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\karin\AppData\Local\Temp\pip-install-hft_9e6h\pythonnet\setup.py", line 18, in <module>
        from wheel import bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I figured out I need to install the pypi 'wheel' package:
```
C:\Users\karin>pip install wheel
Collecting wheel
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2
```

After that, I tried installing the pywebview pypi package again and got this error:
```
C:\Users\karin>pip install pywebview
Collecting pywebview
  Using cached pywebview-3.2-py3-none-any.whl (115 kB)
Collecting pythonnet; sys_platform == "win32"
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... -  WARNING: Subprocess output does not appear to be encoded as cp1252
\  WARNING: Subprocess output does not appear to be encoded as cp1252
error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\karin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\karin\AppData\Local\Temp\pip-wheel-3l4cp9x8'
       cwd: C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\
  Complete output (76 lines):
  running bdist_wheel
  running build
  running build_ext
  Es wird auf Updates von https://www.nuget.org/api/v2/ \x81berpr\x81ft.
  "NuGet.exe" 4.1.0 wird zurzeit ausgef\x81hrt.
  "NuGet.exe" wird auf 5.5.1 aktualisiert.
  Das Update war erfolgreich.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
  C:\Users\karin\AppData\Local\Temp\NuGetScratch\p0blgofd.p1c.nugetrestore.targets(435,34): error MSB4092: Ein unerwartetes )-Token wurde an Zeichenposition 28 in der @(PackageReference->Count()) > 0-Bedingung gefunden. [C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\src\runtime\Python.Runtime.csproj]
  C:\Users\karin\AppData\Local\Temp\NuGetScratch\p0blgofd.p1c.nugetrestore.targets(435,34): error MSB4092: Ein unerwartetes )-Token wurde an Zeichenposition 28 in der @(PackageReference->Count()) > 0-Bedingung gefunden. [C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\src\testing\Python.Test.csproj]
  C:\Users\karin\AppData\Local\Temp\NuGetScratch\p0blgofd.p1c.nugetrestore.targets(435,34): error MSB4092: Ein unerwartetes )-Token wurde an Zeichenposition 28 in der @(PackageReference->Count()) > 0-Bedingung gefunden. [C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\src\embed_tests\Python.EmbeddingTest.csproj]
  C:\Users\karin\AppData\Local\Temp\NuGetScratch\p0blgofd.p1c.nugetrestore.targets(435,34): error MSB4092: Ein unerwartetes )-Token wurde an Zeichenposition 28 in der @(PackageReference->Count()) > 0-Bedingung gefunden. [C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\src\console\Console.csproj]
  C:\Users\karin\AppData\Local\Temp\NuGetScratch\p0blgofd.p1c.nugetrestore.targets(435,34): error MSB4092: Ein unerwartetes )-Token wurde an Zeichenposition 28 in der @(PackageReference->Count()) > 0-Bedingung gefunden. [C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\src\clrmodule\clrmodule.csproj]
 
  WARNUNG: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\packages'
 
  NuGet Config files used:
      C:\Users\karin\AppData\Roaming\NuGet\NuGet.Config
 
  Feeds used:
      C:\Users\karin\.nuget\packages\
      https://api.nuget.org/v3/index.json
 
  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 24, in <module>
      from pycparser import c_ast, c_parser
  ModuleNotFoundError: No module named 'pycparser'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\setup.py", line 623, in <module>
      setup(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "C:\Users\karin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\karin\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet, pywebview
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\karin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\karin\AppData\Local\Temp\pip-record-hsgo925p\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\karin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pythonnet'
         cwd: C:\Users\karin\AppData\Local\Temp\pip-install-oz1ikxkp\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
 
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\karin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\karin\\AppData\\Local\\Temp\\pip-install-oz1ikxkp\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\karin\AppData\Local\Temp\pip-record-hsgo925p\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\karin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pythonnet' Check the logs for full command output.
```

Any help would be greatly appreciated, stay healthy :)

**Comment by r0x0r** [comment]
pythonnet does not support Python 3.8 yet. Use 3.7 or 3.6.

**Comment by niklaskeerl** [comment]
It worked using Python 3.7.7, thank you for the quick answer :)
