### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by MaestroMagnifico** [r0x0r/pywebview#527]
### Specification
- pywebview version: 
I don't know. I'm trying to install with command `pip install pywebview`, so latest, I guess.
- platform / version: 
Windows 10, Python 3.8.3

### Description  
I'm trying to install package. First I got error that wheels wasn't found. I installed it. And now I got this:  
```
C:\MyStuff\WORK\PythonProjects\Test3>pip install pywebview
Collecting pywebview
  Using cached pywebview-3.2-py3-none-any.whl (115 kB)
Collecting pythonnet; sys_platform == "win32"
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\maestro\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install-rz7eky8k\\pythonnet\\setup.py'"'"'
; __file__='"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install-rz7eky8k\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(
code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Maestro\AppData\Local\Temp\pip-wheel-dea3ifor'
       cwd: C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\
  Complete output (86 lines):
  running bdist_wheel
  running build
  running build_ext
  Џа®ўҐаЄ  ®Ў­®ў«Ґ­Ё© Ё§ "https://www.nuget.org/api/v2/".
  ‘Ґ©з б § ЇгйҐ­ NuGet.exe 4.1.0.
  ЋЎ­®ў«Ґ­ЁҐ NuGet.exe ў 5.5.1.
  ЋЎ­®ў«Ґ­ЁҐ ўлЇ®«­Ґ­®.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '16.5.0.12403' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\packages'
  
  NuGet Config files used:
      C:\Users\Maestro\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
      C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config
  
  Feeds used:
      C:\Users\Maestro\.nuget\packages\
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  
  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 293, in <module>
      sys.exit(main())
    File "tools\geninterop\geninterop.py", line 273, in main
      python_h = preprocess_python_headers()
    File "tools\geninterop\geninterop.py", line 193, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] Не удается найти указанный файл
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\setup.py", line 623, in <module>
      setup(
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "c:\users\maestro\appdata\local\programs\python\python38-32\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\users\\maestro\\appdata\\local\\programs\\python\\python38-32\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet, pywebview
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\maestro\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install-rz7eky8k\\pythonnet\\setup.py'"'
"'; __file__='"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install-rz7eky8k\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compil
e(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Maestro\AppData\Local\Temp\pip-record-zt7326ac\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\maestro\appdata\local\progra
ms\python\python38-32\Include\pythonnet'
         cwd: C:\Users\Maestro\AppData\Local\Temp\pip-install-rz7eky8k\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\maestro\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install
-rz7eky8k\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Maestro\\AppData\\Local\\Temp\\pip-install-rz7eky8k\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"
'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Maestro\AppData\Local\Temp\pip-record-zt7326ac\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\u
sers\maestro\appdata\local\programs\python\python38-32\Include\pythonnet' Check the logs for full command output.

```
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
No

- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
The underlying dependency `pythonnet` does not support Python 3.8 yet. Use 3.6
