### ISSUE TITLE
pywebview3.2 didn`t work in offical demo 

### ISSUE THREAD

**Issue by ryan3216** [r0x0r/pywebview#544]
### Specification
- pywebview version: 
3.2
- platform / version: 
window7 sp1
python 2.7.18  cefpython3-66.0 pythonnet-2.4.0 pywebview[cef]-3.2
### Description  
  the offical demo didn`t work ("https://pywebview.flowrl.com/examples/js_api.html").
  when I use follow code , pywebview crashed:
  webview.start(gui='cef')
### error message:
File "D:\Program Files\Python27\lib\site-packages\webview\util.py", line 97, in parse_api_js
Traceback (most recent call last):
    func_list = generate_func()
  File "load_handler.pyx", line 20, in cefpython_py27.LoadHandler_OnLoadingStateChange
  File "D:\Program Files\Python27\lib\site-packages\webview\util.py", line 82, in generate_func
  File "D:\Program Files\Python27\lib\site-packages\webview\platforms\cef.py", line 171, in OnLoadingStateChange
    functions = { name: get_args(getattr(window._js_api, name))[1:] for name in dir(window._js_api) if callable(getattr(window._js_api, name)) and not name.startswith('_')}
    instance.initialize()
  File "D:\Program Files\Python27\lib\site-packages\webview\util.py", line 82, in <dictcomp>
    functions = { name: get_args(getattr(window._js_api, name))[1:] for name in dir(window._js_api) if callable(getattr(window._js_api, name)) and not name.startswith('_')}
  File "D:\Program Files\Python27\lib\site-packages\webview\platforms\cef.py", line 94, in initialize
  File "D:\Program Files\Python27\lib\site-packages\webview\util.py", line 78, in get_args
    return list(inspect.getfullargspec(f).args)
AttributeError: 'module' object has no attribute 'getfullargspec'

**Comment by r0x0r** [comment]
Python 2 is last season.

**Comment by ryan3216** [comment]
Hi, thank you for your reply.
Do you mean Python2 is not support?

**Comment by r0x0r** [comment]
Not really. If somebody wants to fix compatibility issues, I accept PRs, but I won’t spend my time on making it compatible with Python2.
