### ISSUE TITLE
Python Runtime Exception: TypeError

### ISSUE THREAD

**Issue by techbox24** [r0x0r/pywebview#560]
### Specification
- pywebview version: 3.3 
- platform / version: Windows10/python 3.7.8 x64

### Description  
  
I'm getting a python Unhandled Exception.
Python.Runtime.PythonException: TypeError : 'str' value cannot be converted to System.Drawing.Color
  at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Threading.ThreadHelper.ThreadStart() 
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Fixed in 3.3.1 already.

**Comment by techbox24** [comment]
Alright how do I install the 3.3.1 update though coz pip install still has only versions up to 3.3?

**Comment by r0x0r** [comment]
Oh my bad, the release did not get through. The fixed version should be on pip now.
