### ISSUE TITLE
Unhandled Python Runtime Exception 

### ISSUE THREAD

**Issue by HackerIndustrial** [r0x0r/pywebview#580]
### Specification
- pywebview version: pywebview==3.3.1 python Python 3.7.8
- platform / version:  windows 10 

### Description  
  
E:\>py test.py

Unhandled Exception: Python.Runtime.PythonException: Exception : Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at Windows.Web.UI.Interop.WebViewControl.Navigate(Uri source)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlHost.Navigate(Uri source)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Navigate(String source)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
test.py is 

  window = webview.create_window('my app',homePath , text_select=True, js_api=api,width=1480, height=800,frameless=False, min_size=(1480,700))

This issue seems to not be present in older versions of python. I am having some trouble debugging since this seems to be a runtime issue and I don't get the usual error 

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by HackerIndustrial** [comment]
I am not running as admin. But my user has admin privileges

**Comment by HackerIndustrial** [comment]
https://pywebview.flowrl.com/guide/renderer.html#gtk-webkit2:

file:// URLs are not fully supported. While such URLs can be loaded, associated resources such as images or stylesheets cannot.
