### ISSUE TITLE
Embedded Exception mistaken for API callable

### ISSUE THREAD

**Issue by jgentil** [r0x0r/pywebview#629]
### Specification
- pywebview version: 3.3.5
- platform / version:  Windows / CEF

### Description  
  
If I have this code:

```
class MyApi:
    class MyException(Exception):
        pass
    def moo(self):
        return 'moo'
```
Passing an instance of MyApi to js_api will result in this error:
```
Traceback (most recent call last):
  File "load_handler.pyx", line 20, in cefpython_py37.LoadHandler_OnLoadingStateChange
  File "~\virtualenvs\dtt-wfEcoP71-py3.7\lib\site-packages\webview\platforms\cef.py", line 180, in OnLoadingStateChange
    instance.initialize()
  File "~\virtualenvs\dtt-wfEcoP71-py3.7\lib\site-packages\webview\platforms\cef.py", line 98, in initialize
    self.browser.ExecuteJavascript(parse_api_js(self.window, 'cef'))
  File "~\virtualenvs\dtt-wfEcoP71-py3.7\lib\site-packages\webview\util.py", line 130, in parse_api_js
    js_code = npo.src + event.src + api.src % (_token, platform, uid, func_list) + dom.src + drag.src % webview.DRAG_REGION_SELECTOR
UnboundLocalError: local variable 'func_list' referenced before assignment
```

This is because line 111 of misidentifies the exception as a Callable.  Since Exceptions, and all class objects, are callable, it tries to include it in the exposed API itself.  https://github.com/r0x0r/pywebview/blob/952b3115c1b3b884e6a4d213a0a031bdea9e6609/webview/util.py#L109-L112

This should probably be using `inspect.ismethod` instead?

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Good call. Merged into master.
