### ISSUE TITLE
Python.Runtime.PythonException: MissingManifestResourceException

### ISSUE THREAD

**Issue by okamiRvS** [r0x0r/pywebview#648]
### Specification
- pywebview version: 3.3.5
- platform / version: Windows Server 2019 Standard Evaluation (version 1809)

### Description  
  I'm opening my web page locally and in windows 7/10 all it works.
![image](https://user-images.githubusercontent.com/33813291/99320472-fd3a4c00-286b-11eb-90e4-293f77f81402.png)

When I open the python script in AWS server it shows me this message:

```
Unhandled Exception: Python.Runtime.PythonException: MissingManifestResourceException : Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.resources" was correctly embedded or linked into assembly "Microsoft.Toolkit.Forms.UI.Controls.WebView" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

It returns me the same error with the [hello world](https://github.com/r0x0r/pywebview#hello-world) too.

  
### Practicalities

- YES/NO I am willing to work on this issue myself.
NO
- YES/NO I am prepared to support this issue financially.
YES

**Comment by r0x0r** [comment]
I have no experience with Python AWS infrastructure. Is it headless?
Some dependency is clearly missing. Does your AWS have GUI stuff bundled?

**Comment by okamiRvS** [comment]
Yes it has a GUI. I connect in RDP mode. Thus, I understand that a dependency is missing, but I don't know how to proceed to find a solution.

**Comment by r0x0r** [comment]
Does searching for `MissingManifestResourceException` of any use?

What .NET version is installed?
