### ISSUE TITLE
CEF exception when destroy a window from JS API call

### ISSUE THREAD

**Issue by maucm92** [r0x0r/pywebview#694]
### Specification
- pywebview version: 3.4
- operating system: Windows 10
- web renderer: CEF

### Description  
When I destroy a window by clicking a button rendered in HTML using the JS API, even though the window seems to close properly, CEF throws an exception:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Python37-32\lib\site-packages\webview\util.py", line 150, in _call
    window.evaluate_js(code)
  File "C:\Python\Python37-32\lib\site-packages\webview\window.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Python\Python37-32\lib\site-packages\webview\window.py", line 280, in evaluate_js
    return self.gui.evaluate_js(escaped_script, self.uid)
  File "C:\Python\Python37-32\lib\site-packages\webview\platforms\winforms.py", line 621, in evaluate_js
    return CEF.evaluate_js(script, uid)
  File "C:\Python\Python37-32\lib\site-packages\webview\platforms\cef.py", line 191, in wrapper
    raise Exception('CEF window with uid {0} does not exist'.format(uid))
Exception: CEF window with uid child_cce7da1e does not exist
```

I would like to know how to avoid this exception and if it is a bug or my code is wrong (if so, a working example would be useful). Any help is greatly appreciated.

Standalone code to reproduce the error: 

```
import webview

#--------------------------------------------------------------------------
# WINDOWS INSTANCES
#--------------------------------------------------------------------------

main_window  = None
child_window = None

#--------------------------------------------------------------------------
# HTML
#--------------------------------------------------------------------------

main_html = """ 
                <h1>Main Window</h1> 
                <button onclick="open_child_window()">Open Child</button>
                <script>
                    function open_child_window() {
                        pywebview.api.open_child_window();
                    } 
                </script>
            """

child_html = """ 
                <h1>Child Window</h1> 
                <button onclick="close_child_window()">Close Child</button>
                <script>
                    function close_child_window() {
                        pywebview.api.close_child_window();
                    } 
                </script>
            """

#--------------------------------------------------------------------------
# APIS
#--------------------------------------------------------------------------
class ChildApi():
    def close_child_window(self):
        global child_window
        child_window.destroy()

class MainApi():
    def open_child_window(self):
        global child_window
        child_api = ChildApi()
        child_window = webview.create_window('Child Window', html=child_html, js_api=child_api, min_size=(600, 450))

#--------------------------------------------------------------------------
# MAIN
#--------------------------------------------------------------------------

if __name__ == '__main__':
    main_api = MainApi()
    main_window = webview.create_window('Main Window', html=main_html, js_api=main_api, min_size=(600, 450))
    webview.start(gui="cef")

```

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry for the late response. I still do not have a Windows machine. See #637 for details.

Anyhow, the bug is fixed in master now. I removed the exception throw.
