### ISSUE TITLE
Problem loading local html on some windows machines

### ISSUE THREAD

**Issue by scullcandyz** [r0x0r/pywebview#719]
- pywebview version:  3.4
- Windows10 (some machines)

### Description  
  
Seems to be a duplicate of #283 happens when compiled & in IDE, where the HTML simply doesnt load and throws a whitescreen. It seems like the path to the HTML file isnt found. 
  
![unknown](https://user-images.githubusercontent.com/58109239/115772687-b2d77100-a3af-11eb-812e-d3d429cf766c.png)

**Comment by r0x0r** [comment]
a) are you using http server or pointing to a local file?
b) could you check what path it is pointing to? (in debug mode)

**Comment by simonrob** [comment]
I've also run into a similar issue on macOS. I'm using pywebview as part of an authentication flow, at the end of which there is a redirection to `localhost`. There is no local web server running, so the connection fails as expected, but I'm using window.loaded and get_current_url() to track when this redirection happens and close the window automatically.

Sometimes, for no reason I can fathom, the localhost redirection simply does nothing - there is no event fired at all, and a blank page is shown as in the screenshot above. The only solution is a system restart - restarting the Python script has no effect.

**Comment by kletel** [comment]
I have the same issue

**Comment by Rafaelh531** [comment]
> I have the same issue

me too

**Comment by r0x0r** [comment]
Please post a minimal example to reproduce this and all the relevant details.

**Comment by nandobfer** [comment]
> Please post a minimal example to reproduce this and all the relevant details.

![image](https://user-images.githubusercontent.com/98974574/188234658-31a8eb16-69ae-4c9e-acfd-f7e5faa23251.png)
this is enough to reproduce it as it gives me the same perma white screen

**Comment by r0x0r** [comment]
@nandobfer 
1. you need pythonnet 3.0 to use pywebview with Python 3.10. It can be installed via `pip install --pre pythonnet`
2. what renderer does it use in your case? try `webview.start(debug=True)`

**Comment by valeriacadavidc** [comment]
I created a desktop app using the Trame cookiecutter, which internally uses PyVista for 3D visualization and pywebview to render the UI in a desktop window.

When I use the plotter_ui component and click the Export HTML or Snapshot button, a new window opens but remains blank, then the entire application freezes and eventually crashes.

This issue occurs only inside the pywebview window of the desktop app. The exported HTML files work fine if opened directly in a browser outside the app.

I would appreciate guidance on how to resolve this problem or work around it.

<img width="1180" height="782" alt="Image" src="https://github.com/user-attachments/assets/5ea61e2b-bc01-4550-a24c-a3d4346df718" />

**Comment by valeriacadavidc** [comment]
I’m using a desktop application created from the Trame cookiecutter template. It integrates PyVista for 3D visualization and pywebview to render the UI inside a desktop window.

When I display a plotter_ui component and click the Export HTML, a new window opens but stays blank, and after the application freezes and crashes. The exported HTML file works fine if I open it directly in a normal browser, the problem only occurs inside the pywebview window.

<img width="610" height="408" alt="Image" src="https://github.com/user-attachments/assets/fbbcad63-6cd8-41dd-a171-90ed065972ba" />

<img width="1208" height="631" alt="Image" src="https://github.com/user-attachments/assets/f30288ea-4f6a-46c8-aa3b-b2dd48c09193" />

Below is the relevant part of my code:

class STLViewer():
    """
    Class for loading and visualizing STL files using PyVista in a Trame interface.
    """

    def __init__(self, server):

        # Get the Trame server instance
        self.server = server
       
        self.pl = pv.Plotter()
        self.view = None
        self.pl.set_background('white')
        self.pl.add_axes()
        self.stl_mesh = None
    
    # -----------
    # Properties
    # -----------

    @property
    def state(self):
        """Access the server state object."""
        return self.server.state

    @property
    def ctrl(self):
        """Access the server controller."""
        return self.server.controller

    def cleanup(self):
        """
        Remove all actors from the plotter and reset the view.
        """
        if self.pl.actors:
            for key, actor in self.pl.actors.items():
                self.pl.remove_actor(actor)

        self.stl_mesh = None
        self.ctrl.clear()
        self.ctrl.view_update()

    def load_stl_file(self, file_path):
        """
        Load an STL file and display it in the PyVista plotter.

        Args:
            file_path (str): Path to the STL file.
        """
        self.cleanup()
        self.stl_mesh = pv.read(file_path)
        self.pl.add_mesh(self.stl_mesh, color="lightblue")
        self.pl.camera_position = 'xy'
        self.pl.reset_camera()
        self.ctrl.view_update()

    def create_ui(self):
        """
        Create the Trame UI for STL visualization.
        """
        with vuetify.VContainer(classes="container-plot-results"):
            with vuetify.VRow(classes="custom-col-results"):
                with vuetify.VCol(cols=12, classes="custom-col-results"):
                    with vuetify.VContainer(fluid=True, classes="container-3d-stl"):
             
                        self.view = plotter_ui(self.pl, mode="server", collapse_menu=True, add_menu=True)
                        self.ctrl.clear = self.view.clear
                        self.ctrl.view_update = self.view.update
                        self.ctrl.reset_camera = self.view.reset_camera


After the program stops running, the following traceback appears. This is not code I wrote, it’s coming from the internal logic that handles the Export HTML functionality in plotter_ui:

Exception raised
RuntimeError('Event loop stopped before Future completed.')
Traceback (most recent call last):
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\protocol.py", line 327, in onCompleteMessage
    results = await results
              ^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\trame_server\protocol.py", line 212, in trigger
    result = fn(*args, **kwargs)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\ui\vuetify3.py", line 231, in attach_export
    return server.protocol.addAttachment(self.export())
                                         ~~~~~~~~~~~^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\ui\base_viewer.py", line 281, in export
    return memoryview(view.export_html())
                      ~~~~~~~~~~~~~~~~^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\views.py", line 90, in export_html
    content = self._plotter().export_html(filename=None)  # type: ignore[union-attr]
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\plotting\plotter.py", line 712, in export_html
    data = self.export_vtksz(filename=None)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\plotting\plotter.py", line 765, in export_vtksz
    elegantly_launch(pyvista.global_theme.trame.jupyter_server_name)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\jupyter.py", line 485, in elegantly_launch
    return asyncio.run(launch_it())
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\nest_asyncio.py", line 96, in run_until_complete
    raise RuntimeError(
        'Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

Error handling request
Traceback (most recent call last):
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\protocol.py", line 327, in onCompleteMessage
    results = await results
              ^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\trame_server\protocol.py", line 212, in trigger
    result = fn(*args, **kwargs)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\ui\vuetify3.py", line 231, in attach_export
    return server.protocol.addAttachment(self.export())
                                         ~~~~~~~~~~~^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\ui\base_viewer.py", line 281, in export
    return memoryview(view.export_html())
                      ~~~~~~~~~~~~~~~~^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\views.py", line 90, in export_html
    content = self._plotter().export_html(filename=None)  # type: ignore[union-attr]
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\plotting\plotter.py", line 712, in export_html
    data = self.export_vtksz(filename=None)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\plotting\plotter.py", line 765, in export_vtksz
    elegantly_launch(pyvista.global_theme.trame.jupyter_server_name)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\pyvista\trame\jupyter.py", line 485, in elegantly_launch
    return asyncio.run(launch_it())
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\nest_asyncio.py", line 96, in run_until_complete
    raise RuntimeError(
        'Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\aiohttp\web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\backends\aiohttp\__init__.py", line 251, in handleWsRequest
    await self.onMessage(is_binary(msg), msg, client_id)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\protocol.py", line 266, in onMessage
    await self.onCompleteMessage(full_message, client_id)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\protocol.py", line 344, in onCompleteMessage
    await self.sendWrappedError(
    ...<9 lines>...
    )
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\wslink\protocol.py", line 475, in sendWrappedError
    await ws.send_bytes(chunk)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\aiohttp\web_ws.py", line 417, in send_bytes
    await self._writer.send_frame(data, WSMsgType.BINARY, compress=compress)
  File "C:\Users\valeria.cadavid\AppData\Local\anaconda3\envs\trame_env_pywebview\Lib\site-packages\aiohttp\_websocket\writer.py", line 125, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport

**Comment by r0x0r** [comment]
Where does pywebview reside in this architecture? How and where do you open a pywebview window?  As pywebview must be run on the main thread, maybe async has something to do with it. Can you launch a new process and run pywebview there?
