### ISSUE TITLE
Exception happen when call pywebview api destory()

### ISSUE THREAD

**Issue by nonew** [r0x0r/pywebview#767]
### Specification
- pywebview version: 3.5
- operating system: Windows 10 Home, 19042.1165
- web renderer: edgechromium

### Description  

When I call to API window.destroy() to close the pywebview window, KeyError: 'master' exception will happen.
  
`import webview
import PySimpleGUI as sg

class WebviewApi:
    def __init__(self):
        self._window = None

    def set_window(self, window):
        self._window = window

    def quit(self):
        self._window.destroy()  **# EXCEPTION happen here**

def custom_logic(window):
    result = window.evaluate_js(
        r"""
        // Register click handler on login button
        var loginBtn = document.getElementById('w3loginbtn')
        loginBtn.addEventListener('click', () => {
            pywebview.api.quit()
        })
        """
    )
    return result

def test(window):
    api = WebviewApi()
    window = webview.create_window('test', 'https://www.w3schools.com/', js_api=api)
    api.set_window(window)
    webview.start(custom_logic, window)

def main():
    layout = [
        [sg.Button('Test', key='-TEST-')]
    ]

    window = sg.Window('Test pywebview', layout)

    while True:
        event, values = window.read()
        if event in (sg.WIN_CLOSED, 'Exit'):
            break
        elif event == '-TEST-':
            test(window)

if __name__ == "__main__":
    main()`
  
**self._window.destroy() raised the following exception:**
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\util.py", line 150, in _call   
    window.evaluate_js(code)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 32, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 286, in evaluate_js
    return self.gui.evaluate_js(escaped_script, self.uid)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\platforms\winforms.py", line 626, in evaluate_js
    return BrowserView.instances[uid].evaluate_js(script)
KeyError: 'master'
  
### Practicalities

- I am willing to provide debug info as much as possible

**Comment by nonew** [comment]
@r0x0r could you please take a look this issue? thanks!

**Comment by nonew** [comment]
@r0x0r 

Here is demo video:
https://user-images.githubusercontent.com/6738220/131865313-e8de860b-85f0-42a2-9c2e-46521ca5d6b1.mp4

"Login" is just a test button for the purpose: 1. Register the click handler in the custom logic, 2. Call pywebview.api.quit() in the custom logic. Unfortunately, an exception occurred when calling pywebview.api.quit() to close the window.
