### ISSUE TITLE
Error: TargetInvocationException

### ISSUE THREAD

**Issue by ArjixWasTaken** [r0x0r/pywebview#798]
### Specification
- pywebview version: 3.5
- operating system: Windows 11
- web renderer: I don't know, I have firefox/chrome/edge installed and didn't specify a renderer

### Description  

I tried running the example code (Hello World) given in the README.md and I get the following error.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

### Practicalities

- I am not willing to work on this issue myself.

- I am not prepared to support this issue financially.

**Comment by ArjixWasTaken** [comment]
I am running on Python 3.8 (64bit) and I installed using pip.

**Comment by ArjixWasTaken** [comment]
Installed `cefpython3` and ran [this](https://pywebview.flowrl.com/examples/cef.html) example code but I am still getting that error.

**Comment by ArjixWasTaken** [comment]
Also installed the [webview2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) and tried running with that but still got the same error.

**Comment by r0x0r** [comment]
Looks like pythonnet issue. Try with Python 3.7 or install a newer pythonnet from its repository
