### ISSUE TITLE
Windows Server Support

### ISSUE THREAD

**Issue by chanchan69** [r0x0r/pywebview#803]
### Specification
- pywebview version: 3.4
- operating system: Windows Server 2019
- web renderer: Microsoft Edge

### Description  
  
  pywebview programs crash with the following stack trace on windows server. I understand that this issue stems from the precompiled webview dlls which pywebview uses. I think the issue is a simple as compiling them with this dependency enabled, but I am not knowledgeable about .net in the slightest. 
`Unhandled Exception: Python.Runtime.PythonException: MissingManifestResourceException : Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.resources" was correctly embedded or linked into assembly "Microsoft.Toolkit.Forms.UI.Controls.WebView" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary 2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

  
### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
EdgeHTML is deprecated both by Microsoft and myself. Can you use EdgeChromium on your Windows Server installation?

**Comment by chanchan69** [comment]
I had the latest version of Edge (the chromium one) installed on that Windows Server install.

**Comment by r0x0r** [comment]
Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.resources is an EdgeHTML dll. It seems it cannot detect EdgeChromium and falls backs to EdgeHTML. pywebview looks for version information from the registry. What do these registry entries look like for Windows Server?
HKLM\SOFTWARE\Microsoft\EdgeUpdate\Clients\x86 / x64 -> pv
and/or
HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\x86 / x64 -> pv

**Comment by chanchan69** [comment]
HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3C4FE00-EFD5-403B-9569-398A20F1BA4A} -> pv = 1.3.153.47

HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062} -> pv = 95.0.1020.44

HKLM\SOFTWARE\Microsoft\EdgeUpdate\Clients does not exist

**Comment by r0x0r** [comment]
Do you have Webview2 Runtime installed? https://pywebview.flowrl.com/guide/installation.html#dependencies

**Comment by chanchan69** [comment]
I installed the Webview2 Runtime via the Evergreen Bootstrapper from https://developer.microsoft.com/en-us/microsoft-edge/webview2/
This resolved the issue completely. Would it be possible for pywebview to detect this specific exception and stack trace and then automatically download the runtime?

**Comment by r0x0r** [comment]
I am not a fan of this approach. It is too specific, nor installing another library automatically is not the job of a library imo. 

This is a useful piece of code though and it would better fit as a separate software or as a plugin. For now I am going to include a download link to the console output if webview2 is not found.
