### ISSUE TITLE
QtWebEngine TypeError: __init__() missing 1 required positional argument: 'localization'

### ISSUE THREAD

**Issue by dzc0d3r** [r0x0r/pywebview#816]
### Specification
- pywebview version: 3.5

- operating system: Ubuntu 20.04 LTS
- web renderer: WebKit 
- Provider : QtWebEngine

### Description  
  
  I'm trying to get started with this boilerplate [pywebview-react-boilerplate](https://github.com/r0x0r/pywebview-react-boilerplate/), when using GTK (WebKit2)  the devtools  work as expected and i can inspect elements, check for any console errors etc , But when i tried to switch to Qt (QtWebEngine) `webview.start(update_ticker, debug=True, gui='qt')` , and i tried to inspect elements i get this error : 
```
Traceback (most recent call last):
  File "/home/User/Playground/pywebview-react-boilerplate/venv-pywebview/lib/python3.8/site-packages/webview/platforms/qt.py", line 131, in show_inspector
    window = Window('web_inspector', title, url, '', 700, 500, None, None, True, False,
TypeError: __init__() missing 1 required positional argument: 'localization'
```

And this the complete Traceback :

```
Traceback (most recent call last):
  File "/home/User/Playground/pywebview-react-boilerplate/venv-pywebview/lib/python3.8/site-packages/webview/platforms/qt.py", line 125, in show_inspector
    BrowserView.instances[uid].raise_()
KeyError: 'master-inspector'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/User/Playground/pywebview-react-boilerplate/venv-pywebview/lib/python3.8/site-packages/webview/platforms/qt.py", line 131, in show_inspector
    window = Window('web_inspector', title, url, '', 700, 500, None, None, True, False,
TypeError: __init__() missing 1 required positional argument: 'localization'
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! pywebview-react-boilerplate@1.0.0 start:default: `./venv-pywebview/bin/python src/index.py`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the pywebview-react-boilerplate@1.0.0 start:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/User/.npm/_logs/2021-11-20T07_16_45_326Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! pywebview-react-boilerplate@1.0.0 start: `npm run frontend:dev && run-script-os`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the pywebview-react-boilerplate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/User/.npm/_logs/2021-11-20T07_16_45_695Z-debug.log
```

  
### Practicalities

- YES I am willing to work on this issue myself.

**Comment by dzc0d3r** [comment]
Sorry For the noise .. this was already fixed here  [#760], i didn't notice until i came across it by chance.
