### ISSUE TITLE
Hello World fails on pythonnet==3.0.0rc4, Python 3.10

### ISSUE THREAD

**Issue by nedsociety** [r0x0r/pywebview#943]
### Specification
- pywebview version: 3.6.3
- operating system: Windows 21H2
- web renderer: edgechromium, I guess?

### Description  

main.py
```py
import webview

window = webview.create_window('Woah dude!', 'https://pywebview.flowrl.com')
webview.start()
```

pyproject.toml (using poetry)
```toml
[tool.poetry.dependencies]
python = "^3.10"
pythonnet = {version = ">=3.0.0rc4", allow-prereleases = true}
htag = "^0.8.0"
pywebview = "^3.6.3"
```

running:
```
$ python main.py

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This issue has been fixed in the master branch
