### ISSUE TITLE
NullReferenceException with pythonnet 3.0.0

### ISSUE THREAD

**Issue by simonrob** [r0x0r/pywebview#961]
### Specification
- pywebview version: 3.6.3
- operating system: Windows 10
- web renderer: EdgeHTML

### Description  
  
Running the example pywebview code with Python 3.10.7 and the recently-released [pythonnet 3.0.0.post1](https://pypi.org/project/pythonnet/3.0.0.post1/) gives an exception (see below). The documentation and warning message note that EdgeHTML is deprecated, but this implies that it should still work currently, even if it will be removed in future. Regardless, I get the same error (without the deprecation warning) even after installing the Edge WebView2 runtime.

```python
> python webviewtest.py
[pywebview] EdgeHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium
 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
  
### Practicalities

- YES I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by sbbosco** [comment]
@simonrob This has been fixed in master, but is not yet part of the current release 3.6.3.
 https://github.com/r0x0r/pywebview/pull/922/files

You can add this 1 line to winforms.py.
```
# webview/platforms/winforms.py

    class BrowserForm(WinForms.Form):
        def __init__(self, window):
            super().__init__()  # add this line
            self.uid = window.uid
```
or downgrade pythonnet and clr_loader
```
# downgrade pythonnet
pip install clr-loader==0.1.7
pip install pythonnet==3.0.0a2
```

**Comment by simonrob** [comment]
Thanks for the quick follow-up - sorry to re-raise an existing fixed issue. I had pythonnet 3.0.0a2 pinned, but not clr_loader 0.1.7. All working now.
