### ISSUE TITLE
Issue Calling Pywebview control in .py script

### ISSUE THREAD

**Issue by computersg** [r0x0r/pywebview#973]
### Specification
I am running Python 3.8 as the pythonnet module will not load in 3.11
- pywebview version:
- 3.6.3,3.0.0a2,0.1.0,0.1.7,1.15.1,2.21
- C:\Users\redacted\AppData\Local\Programs\Python\Python38>python.exe -m pip install pywebview
Requirement already satisfied: pywebview in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (3.6.3)
Requirement already satisfied: pythonnet in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (from pywebview) (3.0.0a2)
Requirement already satisfied: proxy-tools in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (from pywebview) (0.1.0)
Requirement already satisfied: clr-loader in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (from pythonnet->pywebview) (0.1.7)
Requirement already satisfied: cffi>=1.13 in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (from clr-loader->pythonnet->pywebview) (1.15.1)
Requirement already satisfied: pycparser in c:\users\redacted\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.13->clr-loader->pythonnet->pywebview) (2.21)
- operating system:
- Server 2012R2
- web renderer:
- I am unsure

### Description  
  
pywebview will not open a window when the control is called. I create a simple script called welcome.py and used the contents included on the page [https://pywebview.flowrl.com/] for testing purposes. The lines in the script are:

import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()

When I execute the script via a CMD prompt on my Window Server 2012 R2 machine the following error is produced in the CMD window and nothing happens:

Command:
C:\Users\user redacted\AppData\Local\Programs\Python\Python311>python.exe welcome.py

Return
Traceback (most recent call last):
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\welcome.py", line 3, in <module>
    webview.start()
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
             ^^^^^^^^^^^^^^^
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
       ^^^^^^^^^^^^^
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user redacted\AppData\Local\Programs\Python\Python311\Lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

I have run this exact script on a W11 PC and it results in a window opening:
![image](https://user-images.githubusercontent.com/97705760/198133470-5e252157-e3eb-481c-b470-45df03a8f76b.png)

I will note that in order to make it work on the W11 PC I also had to install old versions of pythonnet & clr-loader. Ref: https://stackoverflow.com/questions/74030626/python-pywebview-trouble-with-pythonnet-unbehandelte-ausnahme-system-nullref

Please note I have done the same on the Server 2012 R2 system but it did not resolve the issue. 
 
### Practicalities

- YES/NO I am willing to work on this issue myself.
- YES

- YES/NO I am prepared to support this issue financially.
- Not at this time

**Comment by computersg** [comment]
As a note, I ran the python.exe and executed each line in the script and received the following results:
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import webview
>>> webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
<webview.window.Window object at 0x0000002356427400>
>>> webview.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Users\administrator.HOFFMANTOWN\AppData\Local\Programs\Python\Python3
8\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
>>>
