### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by therealcyber71** [r0x0r/pywebview#975]
### Specification
- pywebview version: 3.6.3
- operating system: windows 11
- web renderer:  none mentioned

### Description  
  
  II tried the example on the docs site and got this error:
![image](https://user-images.githubusercontent.com/72592470/199041796-c66619c0-5389-4e08-a757-40cc41e8f584.png)

  ```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
### Practicalities

- YES/NO I am willing to work on this issue myself NO

- YES/NO I am prepared to support this issue financially NO

**Comment by therealcyber71** [comment]
Hey, thanks a lot, this solution worked!!
