### ISSUE TITLE
qt6: QApplication.desktop was removed

### ISSUE THREAD

**Issue by cybergrind** [r0x0r/pywebview#993]
### Specification
- pywebview version: 3.6.3
- operating system: Linux
- web renderer: qt6

### Description  

```
Traceback (most recent call last):
  File "/home/kpi/devel/client/venv/lib/python3.10/site-packages/webview/platforms/qt.py", line 633, in on_create_window
    func()
  File "/home/kpi/devel/client/venv/lib/python3.10/site-packages/webview/platforms/qt.py", line 638, in _create
    browser = BrowserView(window)
  File "/home/kpi/devel/client/venv/lib/python3.10/site-packages/webview/platforms/qt.py", line 323, in __init__
    center = QApplication.desktop().availableGeometry().center() - self.rect().center()
AttributeError: type object 'QApplication' has no attribute 'desktop'
```  

  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by sbbosco** [comment]
@cybergrind This is fixed in the latest version of **pywebview** which is 3.7.2. I haven't tested it on Linux, but the latest version fixed the same problem on Windows.

**Comment by cybergrind** [comment]
@sbbosco yeah, thank you! I've checked in master but probably a wrong line

my bad, sorry for the noise
