### ISSUE TITLE
nuitka compile exe run error 

### ISSUE THREAD

**Issue by masonwu21** [r0x0r/pywebview#998]
nuitka --standalone --output-dir=output .\js_api.py  

PS D:\Work\PatternConverter\output\js_api.dist> .\js_api.exe
Traceback (most recent call last):
  File "D:\Work\PatternConverter\output\js_api.dist\inspect.py", line 37, in <module>
  File "D:\Work\PatternConverter\output\js_api.dist\ast.py", line 29, in <module>
  File "D:\Work\PatternConverter\output\js_api.dist\contextlib.py", line 5, in <module>
  File "D:\Work\PatternConverter\output\js_api.dist\collections\__init__.py", line 36, in <module>
  File "D:\Work\PatternConverter\output\js_api.dist\operator.py", line 1, in <module operator>
  File "D:\Work\PatternConverter\output\js_api.dist\re.py", line 127, in <module>
  File "D:\Work\PatternConverter\output\js_api.dist\functools.py", line 18, in <module>
ImportError: cannot import name 'namedtuple' from partially initialized module 'collections' (most likely due to a circular import) (D:\Work\PatternConverter\output\js_api.dist\collections\__init__.py)
PS D:\Work\PatternConverter\output\js_api.dist>

**Comment by r0x0r** [comment]
Judging by the stacktrace, the error is in your code. Something I cannot help with.
